import { NextRequest } from 'next/server';
import { authContext, requirePermission } from '@/lib/auth';
import { fail, ok } from '@/lib/http';
import { serviceSupabase } from '@/lib/supabase';
import crypto from 'node:crypto';

const authEmail=(username:string)=>`${username.toLowerCase()}@users.notundigonto.local`;
export async function GET(req:NextRequest){try{const c=await authContext(req);requirePermission(c,'members.view');const sb=serviceSupabase();const u=new URL(req.url);const q=(u.searchParams.get('q')||'').trim();const status=u.searchParams.get('status')||'';const limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50)));let query=sb.from('members').select('*').order('created_at',{ascending:false}).limit(limit);if(status)query=query.eq('status',status);if(q)query=query.or(`member_id.ilike.%${q}%,name_bn.ilike.%${q}%,name_en.ilike.%${q}%,mobile.ilike.%${q}%,nid.ilike.%${q}%`);const {data,error}=await query;if(error)throw error;return ok({ok:true,items:data||[]});}catch(e){return fail(e)}}
export async function POST(req:NextRequest){let authUid='';try{const c=await authContext(req);requirePermission(c,'members.edit');const payload=await req.json();const sb=serviceSupabase();const joinDate=payload.joinDate||new Date().toISOString().slice(0,10);const {data:reserved,error:rerr}=await sb.rpc('nd_next_member_id',{p_join_date:joinDate});if(rerr||!reserved)throw rerr||new Error('Could not reserve member ID.');const memberNo=String(reserved).split('-').at(-1)||crypto.randomInt(1000,9999).toString();const username=`nds${memberNo}`.toLowerCase();const tempPassword=`Nd@${crypto.randomBytes(5).toString('base64url')}9!`;const {data:auth,error:aerr}=await sb.auth.admin.createUser({email:authEmail(username),password:tempPassword,email_confirm:true,user_metadata:{username}});if(aerr||!auth.user)throw aerr||new Error('Could not create login.');authUid=auth.user.id;const {data,error}=await sb.rpc('nd_create_member_core',{p_user_id:c.userId,p_auth_uid:authUid,p_username:username,p_payload:{...payload,reservedMemberId:reserved}});if(error)throw error;return ok({...(data as object),tempPassword},201);}catch(e){if(authUid){try{await serviceSupabase().auth.admin.deleteUser(authUid)}catch{}}return fail(e)}}
