import {NextRequest} from 'next/server';import {authContext,requirePermission} from '@/lib/auth';import {serviceSupabase} from '@/lib/supabase';import {fail,ok} from '@/lib/http';
const id=async(sb:any,key:string,prefix:string,width:number)=>{const {data,error}=await sb.rpc('nd_next_id',{p_sequence_key:key,p_prefix:prefix,p_width:width});if(error)throw error;return data as string};
export async function POST(req:NextRequest){try{const c=await authContext(req),p=await req.json(),sb=serviceSupabase(),now=new Date().toISOString();if(p.action==='meeting.save'){requirePermission(c,'meetings.edit');const mid=p.meetingId||await id(sb,'MEETING','MTG-',7);const row={meeting_id:mid,type:p.type||'GENERAL',title:p.title||'',date:p.date||new Date().toISOString().slice(0,10),time:p.time||'',venue:p.venue||'',agenda:p.agenda||'',minutes:p.minutes||'',resolution_no:p.resolutionNo||'',status:p.status||'SCHEDULED',updated_at:now,updated_by:c.userId,...(!p.meetingId?{created_at:now,created_by:c.userId}:{})};const {error}=await sb.from('meetings').upsert(row);if(error)throw error;await sb.rpc('nd_create_audit',{p_user_id:c.userId,p_action:p.meetingId?'UPDATE':'CREATE',p_entity_type:'MEETING',p_entity_id:mid,p_old:'{}',p_new:row,p_reason:'Meeting saved'});return ok({ok:true,meetingId:mid})}
if(p.action==='attendance.save'){requirePermission(c,'meetings.edit');if(!p.meetingId||!p.memberId)throw new Error('Meeting and member required.');const {data:old}=await sb.from('meeting_attendance').select('*').eq('meeting_id',p.meetingId).eq('member_id',p.memberId).maybeSingle();const aid=old?.attendance_id||await id(sb,'ATTENDANCE','ATD-',8);const row={attendance_id:aid,meeting_id:p.meetingId,member_id:p.memberId,status:p.status||'PRESENT',note:p.note||'',updated_at:now,updated_by:c.userId,...(!old?{created_at:now,created_by:c.userId}:{})};const {error}=await sb.from('meeting_attendance').upsert(row);if(error)throw error;return ok({ok:true,attendanceId:aid})}
if(p.action==='committee.add'){requirePermission(c,'committee.edit');const cid=await id(sb,'COMMITTEE','COM-',7);const row={committee_id:cid,member_id:p.memberId,designation:p.designation||'',start_date:p.startDate||new Date().toISOString().slice(0,10),end_date:p.endDate||null,status:p.status||'ACTIVE',notes:p.notes||'',created_at:now,created_by:c.userId};const {error}=await sb.from('committee').insert(row);if(error)throw error;return ok({ok:true,committeeId:cid})}
if(p.action==='notification.broadcast'){if(c.roleId!=='ADMIN')throw new Error('FORBIDDEN');const title=String(p.title||'').trim().slice(0,160),message=String(p.message||'').trim().slice(0,2000);if(!title||!message)throw new Error('Title and message required.');if(p.memberId){const nid=await id(sb,'NOTIFICATION','NTF-',7);await sb.from('notifications').insert({notification_id:nid,user_id:'',member_id:p.memberId,type:p.type||'NOTICE',title,message,status:'UNREAD',created_at:now});}else{const {data:users}=await sb.from('users').select('user_id,member_id').eq('status','ACTIVE');const rows=[];for(const u of users||[])rows.push({notification_id:await id(sb,'NOTIFICATION','NTF-',7),user_id:u.user_id,member_id:u.member_id||'',type:p.type||'NOTICE',title,message,status:'UNREAD',created_at:now});if(rows.length)await sb.from('notifications').insert(rows);}return ok({ok:true})}
if(p.action==='finance.withdraw'){requirePermission(c,'accounts.edit');const {data,error}=await sb.rpc('nd_withdraw_savings',{p_user_id:c.userId,p_payload:p.payload||{}});if(error)throw error;return ok(data)}
if(p.action==='finance.transfer'){requirePermission(c,'accounts.edit');const {data,error}=await sb.rpc('nd_transfer_funds',{p_user_id:c.userId,p_payload:p.payload||{}});if(error)throw error;return ok(data)}
if(p.action==='expense.preview'){if(!(c.roleId==='ADMIN'||c.permissions.includes('accounts.view')||c.permissions.includes('accounts.edit')))throw new Error('FORBIDDEN');const {data,error}=await sb.rpc('nd_preview_unit_expense',{p_amount:p.amount,p_date:p.date||new Date().toISOString().slice(0,10)});if(error)throw error;return ok(data)}
throw new Error('Unknown management action.')}catch(e){return fail(e)}}
