export type Lang = 'bn' | 'en';
export const dictionary = {
  bn: {
    app:'নতুন দিগন্ত', tagline:'একসাথে সঞ্চয়, উন্নত আগামীর পথে', dashboard:'ড্যাশবোর্ড', members:'সদস্য', savings:'সঞ্চয়', receipts:'রসিদ', loans:'ঋণ', investments:'বিনিয়োগ', profits:'মুনাফা', finance:'হিসাব', meetings:'সভা', documents:'ডকুমেন্ট', reports:'রিপোর্ট', notifications:'নোটিফিকেশন', users:'ব্যবহারকারী', audit:'অডিট', settings:'সেটিংস', logout:'লগআউট', language:'English', totalMembers:'মোট সদস্য', activeLoans:'সক্রিয় ঋণ', todayCollection:'আজকের আদায়', totalSavings:'মোট সঞ্চয়', cashBank:'ক্যাশ/ব্যাংক', recentTransactions:'সাম্প্রতিক লেনদেন', addMember:'নতুন সদস্য', collectSavings:'সঞ্চয় গ্রহণ', applyLoan:'ঋণ আবেদন', loading:'লোড হচ্ছে…', search:'খুঁজুন', name:'নাম', mobile:'মোবাইল', status:'স্ট্যাটাস', amount:'পরিমাণ', date:'তারিখ', action:'অ্যাকশন', save:'সংরক্ষণ', cancel:'বাতিল', memberId:'সদস্য আইডি', monthlyDue:'মাসিক বকেয়া', units:'ইউনিট', paymentAccount:'পেমেন্ট অ্যাকাউন্ট', paymentMethod:'পেমেন্ট পদ্ধতি', reference:'রেফারেন্স', extraSavings:'অতিরিক্ত সঞ্চয়', selectedMonths:'নির্বাচিত মাস', noData:'কোনো তথ্য নেই', welcome:'স্বাগতম', fastSecure:'দ্রুত • নিরাপদ • অডিটযোগ্য', role:'রোল', requested:'আবেদনকৃত', outstanding:'বকেয়া', type:'ধরন', purpose:'উদ্দেশ্য', login:'লগইন', username:'ইউজারনেম', password:'পাসওয়ার্ড', signIn:'প্রবেশ করুন', loginHint:'আপনার অনুমোদিত ইউজারনেম ও পাসওয়ার্ড ব্যবহার করুন।'
  },
  en: {
    app:'Notun Digonto', tagline:'Saving together, toward a better tomorrow', dashboard:'Dashboard', members:'Members', savings:'Savings', receipts:'Receipts', loans:'Loans', investments:'Investments', profits:'Profit', finance:'Finance', meetings:'Meetings', documents:'Documents', reports:'Reports', notifications:'Notifications', users:'Users', audit:'Audit', settings:'Settings', logout:'Logout', language:'বাংলা', totalMembers:'Total members', activeLoans:'Active loans', todayCollection:"Today's collection", totalSavings:'Total savings', cashBank:'Cash / Bank', recentTransactions:'Recent transactions', addMember:'Add member', collectSavings:'Collect savings', applyLoan:'Apply loan', loading:'Loading…', search:'Search', name:'Name', mobile:'Mobile', status:'Status', amount:'Amount', date:'Date', action:'Action', save:'Save', cancel:'Cancel', memberId:'Member ID', monthlyDue:'Monthly due', units:'Units', paymentAccount:'Payment account', paymentMethod:'Payment method', reference:'Reference', extraSavings:'Extra savings', selectedMonths:'Selected months', noData:'No data found', welcome:'Welcome', fastSecure:'Fast • secure • auditable', role:'Role', requested:'Requested', outstanding:'Outstanding', type:'Type', purpose:'Purpose', login:'Login', username:'Username', password:'Password', signIn:'Sign in', loginHint:'Use your authorized username and password.'
  }
} as const;
export type I18nKey = keyof typeof dictionary.en;
export function t(lang: Lang, key: I18nKey) { return dictionary[lang][key] ?? key; }
