import { createHash, randomBytes } from 'node:crypto';
import { serviceSupabase, publicSupabase } from './supabase';

export type LegacySession={sessionId:string,userId:string,memberId:string,fullName:string,username:string,role:string,permissions:string[],mustChangePassword:boolean,expiresAt:string,authUid?:string};
export const sb=()=>serviceSupabase();
export const pub=()=>publicSupabase();
export const now=()=>new Date().toISOString();
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:0};
export const round2=(v:any)=>Math.round((num(v)+Number.EPSILON)*100)/100;
export const bool=(v:any)=>v===true||String(v||'').toUpperCase()==='TRUE'||String(v)==='1';
export const dateOnly=(v:any)=>{if(!v)return '';const s=String(v);const m=s.match(/^\d{4}-\d{2}-\d{2}/);if(m)return m[0];const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(d):''};
export const monthOnly=(v:any)=>dateOnly(v).slice(0,7);
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export const normalizeUsername=(v:any)=>String(v||'').trim().toLowerCase();
export const authEmail=(u:string)=>`${normalizeUsername(u).replace(/[^a-z0-9._-]/g,'')}@users.notundigonto.local`;
export const mobileKey=(v:any)=>{let d=String(v??'').trim().replace(/\D/g,'');if(!d)return '';if(d.startsWith('00880'))d=d.slice(2);if(d.startsWith('880')&&d.length===13&&d[3]==='1')return '0'+d.slice(3);if(d.length===10&&d[0]==='1')return '0'+d;return d};
export const normalizeMobile=(v:any,required=false)=>{const raw=String(v||'').trim();if(!raw){if(required)throw new Error('মোবাইল নম্বর আবশ্যক।');return ''}if(!/^\+?[0-9][0-9\s().-]{6,20}$/.test(raw))throw new Error('মোবাইল নম্বর সঠিক নয়।');const d=raw.replace(/\D/g,'');if(d.length<7||d.length>15)throw new Error('মোবাইল নম্বর সঠিক নয়।');return raw};
export const normalizeNid=(v:any)=>{const raw=String(v||'').replace(/[\s-]/g,'');if(raw&&!/^\d{8,20}$/.test(raw))throw new Error('NID/Birth Registration নম্বর সঠিক নয়।');return raw};
export const normalizeEmail=(v:any)=>{const raw=String(v||'').trim().toLowerCase();if(raw&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(raw))throw new Error('ইমেইল ঠিকানা সঠিক নয়।');return raw};
export const normalizeBlood=(v:any)=>{const x=String(v||'').trim().toUpperCase();return ['A+','A-','B+','B-','AB+','AB-','O+','O-'].includes(x)?x:''};

export function upperRow(row:any){if(!row)return row;const out:any={};for(const [k,v] of Object.entries(row))out[k.toUpperCase()]=v;return out}
export function upperRows(rows:any[]|null|undefined){return (rows||[]).map(upperRow)}
export function snakePayload(obj:any){const out:any={};for(const [k,v] of Object.entries(obj||{})){out[k.replace(/[A-Z]/g,m=>'_'+m.toLowerCase())]=v}return out}

export async function configMap(){const {data,error}=await sb().from('config').select('key,value');if(error)throw error;return Object.fromEntries((data||[]).map((x:any)=>[x.key,x.value])) as Record<string,string>}
export async function config(key:string,fallback=''){const {data,error}=await sb().from('config').select('value').eq('key',key).maybeSingle();if(error)throw error;return data?.value??fallback}
export async function setConfig(key:string,value:any,userId='SYSTEM'){const {error}=await sb().from('config').update({value:String(value??''),updated_at:now(),updated_by:userId}).eq('key',key);if(error)throw error}
export async function nextId(key:string,prefix:string,width:number){const {data,error}=await sb().rpc('nd_next_id',{p_sequence_key:key,p_prefix:prefix,p_width:width});if(error)throw error;return String(data)}
export async function nextReceipt(){const {data,error}=await sb().rpc('nd_next_receipt_id');if(error)throw error;return String(data)}
export async function nextVoucher(){const {data,error}=await sb().rpc('nd_next_voucher_id');if(error)throw error;return String(data)}
export async function audit(userId:string,action:string,type:string,id:string,oldValue:any,newValue:any,reason=''){const {error}=await sb().rpc('nd_create_audit',{p_user_id:userId,p_action:action,p_entity_type:type,p_entity_id:id,p_old:oldValue??{},p_new:newValue??{},p_reason:reason||''});if(error)throw error}
export async function notify(memberId:string,type:string,title:string,message:string){const {error}=await sb().rpc('nd_create_notification',{p_member_id:memberId||'',p_type:type,p_title:title,p_message:message});if(error)throw error}

export async function sessionFromToken(token:string):Promise<LegacySession>{if(!token)throw new Error('AUTH_REQUIRED');const s=sb();const {data:sess,error}=await s.from('sessions').select('*').eq('token_hash',hash(token)).eq('status','ACTIVE').maybeSingle();if(error||!sess)throw new Error('AUTH_EXPIRED');if(!sess.expires_at||new Date(sess.expires_at).getTime()<=Date.now()){await s.from('sessions').update({status:'EXPIRED',last_seen_at:now()}).eq('session_id',sess.session_id);throw new Error('AUTH_EXPIRED')}const {data:u,error:ue}=await s.from('users').select('*').eq('user_id',sess.user_id).maybeSingle();if(ue||!u||u.status!=='ACTIVE')throw new Error('AUTH_EXPIRED');const {data:r,error:re}=await s.from('roles').select('*').eq('role_id',u.role_id).maybeSingle();if(re||!r||r.status!=='ACTIVE')throw new Error('PERMISSION_DENIED');await s.from('sessions').update({last_seen_at:now()}).eq('session_id',sess.session_id);return {sessionId:sess.session_id,userId:u.user_id,memberId:u.member_id||'',fullName:u.full_name||'',username:u.username,role:u.role_id,permissions:Array.isArray(r.permissions_json)?r.permissions_json:[],mustChangePassword:!!u.must_change_password,expiresAt:sess.expires_at,authUid:u.auth_uid||''}}
export const hasPerm=(s:LegacySession,p:string)=>s.permissions.includes('*')||s.permissions.includes(p);
export function requirePerm(s:LegacySession,p:string){if(!hasPerm(s,p))throw new Error('PERMISSION_DENIED: '+p)}
export function requireAdmin(s:LegacySession){if(s.role!=='ADMIN')throw new Error('PERMISSION_DENIED: ADMIN')}

export async function revokeUserSessions(userId:string,except=''){const q=await sb().from('sessions').select('session_id,status').eq('user_id',userId);if(q.error)throw q.error;const ids=(q.data||[]).filter((x:any)=>x.status==='ACTIVE'&&(!except||x.session_id!==except)).map((x:any)=>x.session_id);if(ids.length){const {error}=await sb().from('sessions').update({status:'REVOKED',last_seen_at:now()}).in('session_id',ids);if(error)throw error}return ids.length}

export async function loginUser(usernameRaw:string,password:string){const username=normalizeUsername(usernameRaw);if(!username||!password)throw new Error('Username and password are required.');const s=sb(),cm=await configMap();const max=Math.max(3,num(cm.LOGIN_MAX_ATTEMPTS||5)),mins=Math.max(1,num(cm.LOGIN_LOCK_MINUTES||15));let cutoff=Date.now()-mins*60000;if(cm.LOGIN_LOCK_RESET_AT){const x=new Date(cm.LOGIN_LOCK_RESET_AT).getTime();if(Number.isFinite(x)&&x>cutoff)cutoff=x}const {data:recent}=await s.from('login_log').select('success,created_at').eq('username',username).eq('action','LOGIN').gte('created_at',new Date(cutoff).toISOString()).order('created_at',{ascending:false}).limit(max+5);let failures=0;for(const x of recent||[]){if(x.success)break;if(++failures>=max)throw new Error('অনেকবার ভুল লগইন চেষ্টা হয়েছে। কিছুক্ষণ পর আবার চেষ্টা করুন।')}const {data:u}=await s.from('users').select('*').eq('username',username).maybeSingle();const log=async(ok:boolean,msg:string)=>{try{await s.from('login_log').insert({login_id:await nextId('LOGIN','LOG-',8),user_id:u?.user_id||'',username,action:'LOGIN',success:ok,message:msg,created_at:now()})}catch{}};if(!u||u.status!=='ACTIVE'){await log(false,'Invalid username or inactive account');throw new Error('ইউজারনেম বা পাসওয়ার্ড সঠিক নয়।')}const {error:ae}=await pub().auth.signInWithPassword({email:authEmail(username),password:String(password)});if(ae){await log(false,'Invalid password');throw new Error('ইউজারনেম বা পাসওয়ার্ড সঠিক নয়।')}const token=randomBytes(48).toString('hex'),hours=Math.max(1,num(cm.SESSION_HOURS||6)),expires=new Date(Date.now()+hours*3600000).toISOString(),sessionId=await nextId('SESSION','SES-',8);const {error:se}=await s.from('sessions').insert({session_id:sessionId,token_hash:hash(token),user_id:u.user_id,created_at:now(),expires_at:expires,last_seen_at:now(),status:'ACTIVE'});if(se)throw se;await s.from('users').update({last_login_at:now(),updated_at:now(),updated_by:u.user_id}).eq('user_id',u.user_id);await log(true,'Success');const sess=await sessionFromToken(token);return {token,session:sess,mustChangePassword:!!u.must_change_password}}

export async function bootstrap(sess:LegacySession){const cm=await configMap();let accounts:any[]=[];if(sess.role!=='MEMBER'){const {data,error}=await sb().from('bank_accounts').select('*').eq('status','ACTIVE').order('account_id');if(error)throw error;accounts=(data||[]).map((r:any)=>({id:r.account_id,code:r.account_code,name:r.account_name,type:r.type,bank:r.bank_name,number:r.account_no}))}return {session:sess,config:{nameBn:cm.SOCIETY_NAME_BN||'নতুন দিগন্ত সঞ্চয় সমিতি',nameEn:cm.SOCIETY_NAME_EN||'Notun Digonto Sanchoy Samity',estd:cm.ESTD_YEAR||'2026',tagline:cm.TAGLINE_BN||'',currency:cm.CURRENCY_SYMBOL||'৳',language:cm.APP_LANGUAGE||'bn',unitAmount:num(cm.MONTHLY_UNIT_AMOUNT||1000),dueDay:num(cm.MONTHLY_DUE_DAY||10),societyStartMonth:cm.SOCIETY_START_MONTH||'2026-08'},accounts,dashboard:null,version:'1.1.6'}}

export async function accountById(id:string){const {data,error}=await sb().from('bank_accounts').select('*').eq('account_id',id).eq('status','ACTIVE').maybeSingle();if(error||!data)throw new Error('Account not found.');return data}
export async function accountBalances(){const {data,error}=await sb().from('bank_accounts').select('*').eq('status','ACTIVE').order('account_id');if(error)throw error;return Promise.all((data||[]).map(async(a:any)=>{const {data:b,error:e}=await sb().rpc('nd_account_balance',{p_account_id:a.account_id});if(e)throw e;return {id:a.account_id,code:a.account_code,name:a.account_name,type:a.type,balance:round2(b),bank:a.bank_name,number:a.account_no}}))}
export async function memberSavings(memberId:string){const {data,error}=await sb().rpc('nd_member_savings_balance',{p_member_id:memberId});if(error)throw error;return round2(data)}
export async function currentDue(memberId:string){const {data,error}=await sb().rpc('nd_current_due_balance',{p_member_id:memberId});if(error)throw error;return round2(data)}
export async function savingsAdvance(memberId:string){const {data,error}=await sb().rpc('nd_savings_advance',{p_member_id:memberId});if(error)throw error;return round2(data)}
export async function loanOutstanding(memberId:string){const {data,error}=await sb().from('loans').select('outstanding_principal').eq('member_id',memberId);if(error)throw error;return round2((data||[]).reduce((z:any,x:any)=>z+num(x.outstanding_principal),0))}
export async function currentUnit(memberId:string,date=today()){const month=date.slice(0,7);const {data,error}=await sb().rpc('nd_savings_unit_for_month',{p_member_id:memberId,p_month:month});if(error)throw error;return data?upperRow(data):null}

export async function storeDataUrl(dataUrl:string,bucket:'member-photos'|'documents',baseName:string){if(!dataUrl)return {path:'',mime:'',name:''};const m=String(dataUrl).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error('Invalid file data.');const mime=m[1].toLowerCase();const img=['image/jpeg','image/png','image/webp'];if(bucket==='member-photos'&&!img.includes(mime))throw new Error('Only JPG, PNG or WebP images are allowed.');if(bucket==='documents'&&![...img,'application/pdf'].includes(mime))throw new Error('Only JPG, PNG, WebP or PDF files are allowed.');const buf=Buffer.from(m[2],'base64');if(buf.length>5*1024*1024&&bucket==='member-photos')throw new Error('File too large. Max 5 MB.');if(buf.length>15*1024*1024&&bucket==='documents')throw new Error('File too large. Max 15 MB.');const ext=(mime.split('/')[1]||'bin').replace('jpeg','jpg').replace(/[^a-z0-9]/gi,'');const safe=baseName.replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,100)||'file';const path=`${new Date().toISOString().slice(0,10)}/${safe}_${randomBytes(4).toString('hex')}.${ext}`;const {error}=await sb().storage.from(bucket).upload(path,buf,{contentType:mime,upsert:false});if(error)throw error;return {path,mime,name:path.split('/').pop()||safe}}
export async function storageDataUri(bucket:'member-photos'|'documents',path:string){if(!path)return '';const {data,error}=await sb().storage.from(bucket).download(path);if(error||!data)return '';const ab=await data.arrayBuffer();const mime=(data as any).type||'application/octet-stream';return `data:${mime};base64,${Buffer.from(ab).toString('base64')}`}

export function monthRange(start:string,end:string,max=120){if(!/^\d{4}-\d{2}$/.test(start)||!/^\d{4}-\d{2}$/.test(end)||start>end)throw new Error('Invalid month range.');const out:string[]=[];let [y,m]=start.split('-').map(Number);const [ey,em]=end.split('-').map(Number);while(y<ey||(y===ey&&m<=em)){out.push(`${y}-${String(m).padStart(2,'0')}`);if(out.length>max)throw new Error('Too many months selected.');m++;if(m===13){m=1;y++}}return out}
export function endOfMonth(month:string){const [y,m]=month.slice(0,7).split('-').map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}
export function randomPassword(){return `Nd@${randomBytes(6).toString('base64url')}9!`}
