import fs from 'node:fs';import path from 'node:path';
const root=process.cwd();
const need=['package.json','app/page.tsx','app/login/page.tsx','app/api/legacy/route.ts','lib/legacy.ts','lib/legacy-call.ts','public/legacy/index.html','supabase/migrations/001_schema.sql','supabase/migrations/002_seed_defaults.sql','supabase/migrations/003_core_rules.sql','supabase/migrations/004_financial_rules.sql','supabase/migrations/005_investment_profit_rules.sql','supabase/migrations/006_parity_finance_rules.sql','supabase/migrations/007_storage.sql','supabase/migrations/008_parity_performance_permissions.sql','legacy_reference/Code.gs','legacy_reference/ui/Index.html','legacy_reference/ui/Module1.html','legacy_reference/ui/Module2.html','legacy_reference/ui/Module3.html'];
let errors=[];for(const f of need)if(!fs.existsSync(path.join(root,f)))errors.push(`missing ${f}`);
const schema=fs.readFileSync(path.join(root,'supabase/migrations/001_schema.sql'),'utf8');const tables=[...schema.matchAll(/create table if not exists public\.(\w+)/g)].map(x=>x[1]);if(tables.length!==39)errors.push(`expected 39 legacy tables, found ${tables.length}`);
for(const f of fs.readdirSync(path.join(root,'supabase/migrations')).filter(x=>x.endsWith('.sql'))){const s=fs.readFileSync(path.join(root,'supabase/migrations',f),'utf8');if((s.match(/\$\$/g)||[]).length%2)errors.push(`${f}: unbalanced $$`);if((s.match(/\(/g)||[]).length!==(s.match(/\)/g)||[]).length)errors.push(`${f}: unbalanced parentheses`);if(/raise exception case/i.test(s))errors.push(`${f}: unsupported RAISE EXCEPTION CASE`);}
const ui=fs.readFileSync(path.join(root,'public/legacy/index.html'),'utf8');if(!ui.includes('ndVercelBridge')||!ui.includes("fetch('/api/legacy'"))errors.push('legacy UI bridge missing');for(const id of ['ndAuthCore','ndAppCore','ndModule1','ndModule2','ndModule3','ndUiReady'])if(!ui.includes(`id="${id}"`))errors.push(`legacy UI bundle missing ${id}`);
const uiCalls=new Set([...ui.matchAll(/\bapi\(\s*['\"]([^'\"]+)/g)].map(m=>m[1]));uiCalls.add('loginAndBootstrap');
const backend=fs.readFileSync(path.join(root,'lib/legacy-call.ts'),'utf8');const declarations=new Set([...backend.matchAll(/async function\s+([A-Za-z0-9_]+)\s*\(/g)].map(m=>m[1]));
const dm=backend.match(/const LEGACY_CALLS:[\s\S]*?=\{([\s\S]*?)\n\};/);const dispatched=new Set(dm?[...dm[1].matchAll(/\b([A-Za-z_][A-Za-z0-9_]*)\b/g)].map(m=>m[1]):[]);
for(const fn of uiCalls){if(!declarations.has(fn))errors.push(`UI RPC missing implementation: ${fn}`);if(!dispatched.has(fn))errors.push(`UI RPC missing dispatcher mapping: ${fn}`)}
const route=fs.readFileSync(path.join(root,'app/api/legacy/route.ts'),'utf8');if(!route.includes('callLegacy'))errors.push('legacy API route is not wired to dispatcher');
if(errors.length){console.error(errors.join('\n'));process.exit(1)}
console.log(`OK: ${tables.length} legacy tables; ${uiCalls.size}/${uiCalls.size} UI RPC calls implemented and dispatched; ${need.length} parity files present; SQL delimiters/parentheses balanced.`);
