-- Savings collection, loans, income and expense posting.

create or replace function public.nd_collect_savings(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  m public.members; account public.bank_accounts; amount_v numeric; type_v text; date_v date; note_v text; txn_id_v text; receipt_id_v text;
  description_v text; months_v text[]; society_start text; start_m text; end_m text; cur_d date; total_outstanding numeric:=0; remaining numeric; due public.monthly_dues; applied numeric; paid numeric; bal numeric; batch_id text:='';
  txn_ids jsonb:='[]'::jsonb; receipt_ids jsonb:='[]'::jsonb; allocations jsonb:='[]'::jsonb; month_v text; payment_method_v text; reference_v text;
begin
  select * into m from public.members where member_id=p_payload->>'memberId' for update;
  if m.member_id is null or m.status<>'ACTIVE' then raise exception 'সক্রিয় সদস্য পাওয়া যায়নি।'; end if;
  amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'জমার পরিমাণ ০-এর বেশি হতে হবে।'; end if;
  type_v:=case when upper(coalesce(p_payload->>'type',''))='EXTRA_SAVINGS' then 'EXTRA_SAVINGS' else 'MONTHLY_SAVINGS' end;
  select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-CASH') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if;
  date_v:=coalesce(nullif(p_payload->>'date','')::date,public.nd_today()); note_v:=trim(coalesce(p_payload->>'notePurpose',p_payload->>'note','')); if length(note_v)>500 then raise exception 'Note / Purpose must be within 500 characters.'; end if;
  payment_method_v:=coalesce(nullif(p_payload->>'paymentMethod',''),account.type); reference_v:=coalesce(p_payload->>'reference','');

  if type_v='EXTRA_SAVINGS' then
    txn_id_v:=public.nd_next_id('TXN','TRX-',8); receipt_id_v:=public.nd_next_receipt_id(); description_v:='অতিরিক্ত সঞ্চয়'||case when note_v<>'' then ' · '||note_v else '' end;
    insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by,note_purpose)
    values(txn_id_v,date_v,m.member_id,'EXTRA_SAVINGS','SAVINGS',description_v,'CREDIT',amount_v,amount_v,0,0,account.account_id,payment_method_v,reference_v,'',receipt_id_v,'POSTED',coalesce(p_payload->>'parentTxnId',''),coalesce(p_payload->>'correctionReason',''),now(),p_user_id,now(),p_user_id,note_v);
    insert into public.receipts(receipt_id,txn_id,member_id,receipt_date,amount,purpose,payment_method,reference,status,print_count,created_at,created_by)
    values(receipt_id_v,txn_id_v,m.member_id,date_v,amount_v,'অতিরিক্ত সঞ্চয়'||case when note_v<>'' then ' · উদ্দেশ্য: '||note_v else '' end,payment_method_v,reference_v,'ACTIVE',0,now(),p_user_id);
    perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',amount_v,'credit',0),jsonb_build_object('accountCode',(public.nd_coa_by_system('MEMBER_SAVINGS')).account_code,'debit',0,'credit',amount_v)),m.member_id,'',description_v);
    perform public.nd_create_audit(p_user_id,'COLLECT','TRANSACTION',txn_id_v,'{}'::jsonb,(select to_jsonb(t) from public.transactions t where txn_id=txn_id_v),'Extra savings collection');
    perform public.nd_create_notification(m.member_id,'PAYMENT','সঞ্চয় জমা হয়েছে',receipt_id_v||' | '||amount_v||' টাকা অতিরিক্ত সঞ্চয় জমা হয়েছে।');
    return jsonb_build_object('ok',true,'txnId',txn_id_v,'receiptId',receipt_id_v,'receiptIds',jsonb_build_array(receipt_id_v),'txnIds',jsonb_build_array(txn_id_v),'amount',amount_v,'memberId',m.member_id,'notePurpose',note_v,'multi',false);
  end if;

  society_start:=public.nd_config('SOCIETY_START_MONTH','2026-08');
  if jsonb_typeof(p_payload->'months')='array' and jsonb_array_length(p_payload->'months')>0 then
    select array_agg(x order by x) into months_v from (select distinct left(value,7) x from jsonb_array_elements_text(p_payload->'months') where left(value,7)~'^\d{4}-\d{2}$' and left(value,7)>=society_start) q;
  elsif coalesce(p_payload->>'startMonth','')<>'' or coalesce(p_payload->>'endMonth','')<>'' then
    start_m:=left(coalesce(nullif(p_payload->>'startMonth',''),p_payload->>'endMonth'),7); end_m:=left(coalesce(nullif(p_payload->>'endMonth',''),p_payload->>'startMonth'),7);
    if start_m>end_m then month_v:=start_m; start_m:=end_m; end_m:=month_v; end if;
    select array_agg(to_char(g,'YYYY-MM')) into months_v from generate_series((start_m||'-01')::date,(end_m||'-01')::date,interval '1 month') g where to_char(g,'YYYY-MM')>=society_start limit 120;
  else
    month_v:=left(coalesce(nullif(p_payload->>'month',''),to_char(date_v,'YYYY-MM')),7); if month_v>=society_start then months_v:=array[month_v]; end if;
  end if;
  if months_v is null or cardinality(months_v)=0 then raise exception 'সঠিক সঞ্চয়ের মাস নির্বাচন করুন। হিসাব শুরু % থেকে।',society_start; end if;

  foreach month_v in array months_v loop
    perform public.nd_ensure_monthly_due(m.member_id,month_v,p_user_id);
    select * into due from public.monthly_dues where member_id=m.member_id and due_month=month_v and status<>'MERGED' limit 1 for update;
    if due.due_id is null then raise exception '% মাসের জন্য সঞ্চয় ইউনিট পাওয়া যায়নি।',month_v; end if;
    total_outstanding:=total_outstanding+greatest(0,due.balance);
  end loop;
  total_outstanding:=round(total_outstanding,2); if total_outstanding<=0 then raise exception 'নির্বাচিত মাসগুলোতে কোনো বকেয়া নেই।'; end if; if amount_v>total_outstanding+0.01 then raise exception 'নির্বাচিত মাসগুলোর মোট বকেয়া % টাকা। অতিরিক্ত টাকা হলে “অতিরিক্ত সঞ্চয়” অপশন ব্যবহার করুন অথবা আরও মাস নির্বাচন করুন।',total_outstanding; end if;
  remaining:=amount_v; if cardinality(months_v)>1 then batch_id:=public.nd_next_id('SAVINGS_BATCH','BAT-',8); end if;

  foreach month_v in array months_v loop
    exit when remaining<=0.001;
    select * into due from public.monthly_dues where member_id=m.member_id and due_month=month_v and status<>'MERGED' limit 1 for update;
    if due.balance<=0 then continue; end if;
    applied:=round(least(remaining,due.balance),2); if applied<=0 then continue; end if;
    txn_id_v:=public.nd_next_id('TXN','TRX-',8); receipt_id_v:=public.nd_next_receipt_id(); description_v:=month_v||' মাসের সঞ্চয়';
    insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by,note_purpose)
    values(txn_id_v,date_v,m.member_id,'MONTHLY_SAVINGS','SAVINGS',description_v,'CREDIT',applied,applied,0,0,account.account_id,payment_method_v,reference_v,due.due_id,receipt_id_v,'POSTED',coalesce(nullif(batch_id,''),p_payload->>'parentTxnId',''),coalesce(p_payload->>'correctionReason',''),now(),p_user_id,now(),p_user_id,'');
    paid:=round(due.paid_amount+applied,2); bal:=round(greatest(0,due.due_amount+due.late_fee-paid-due.advance_applied),2);
    update public.monthly_dues set paid_amount=paid,balance=bal,status=case when bal<=0 then 'PAID' else 'PARTIAL' end,updated_at=now(),updated_by=p_user_id where due_id=due.due_id;
    insert into public.receipts(receipt_id,txn_id,member_id,receipt_date,amount,purpose,payment_method,reference,status,print_count,created_at,created_by)
    values(receipt_id_v,txn_id_v,m.member_id,date_v,applied,'মাসিক সঞ্চয় ('||month_v||')',payment_method_v,reference_v,'ACTIVE',0,now(),p_user_id);
    perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',applied,'credit',0),jsonb_build_object('accountCode',(public.nd_coa_by_system('MEMBER_SAVINGS')).account_code,'debit',0,'credit',applied)),m.member_id,due.due_id,description_v);
    txn_ids:=txn_ids||jsonb_build_array(txn_id_v); receipt_ids:=receipt_ids||jsonb_build_array(receipt_id_v); allocations:=allocations||jsonb_build_array(jsonb_build_object('month',month_v,'amount',applied,'txnId',txn_id_v,'receiptId',receipt_id_v)); remaining:=round(remaining-applied,2);
  end loop;
  if remaining>0.01 then raise exception 'Selected months could not absorb the full payment.'; end if;
  perform public.nd_reconcile_savings_dues(m.member_id,p_user_id); perform public.nd_create_audit(p_user_id,'COLLECT',case when jsonb_array_length(allocations)>1 then 'SAVINGS_BATCH' else 'TRANSACTION' end,coalesce(nullif(batch_id,''),txn_ids->>0),'{}'::jsonb,jsonb_build_object('memberId',m.member_id,'months',to_jsonb(months_v),'amount',amount_v,'allocations',allocations),case when jsonb_array_length(allocations)>1 then 'Multi-month savings collection' else 'Monthly savings collection' end); perform public.nd_create_notification(m.member_id,'PAYMENT','মাসিক সঞ্চয় জমা হয়েছে',case when jsonb_array_length(allocations)>1 then jsonb_array_length(allocations)||' মাসে ' else '' end||amount_v||' টাকা জমা হয়েছে।');
  return jsonb_build_object('ok',true,'multi',jsonb_array_length(allocations)>1,'batchId',batch_id,'txnId',txn_ids->>0,'receiptId',receipt_ids->>0,'txnIds',txn_ids,'receiptIds',receipt_ids,'amount',amount_v,'memberId',m.member_id,'allocations',allocations);
end $$;

create or replace function public.nd_loan_eligibility(p_member_id text,p_loan_type text default 'GENERAL')
returns jsonb language plpgsql stable as $$
declare m public.members; months_v integer; min_months numeric; savings_v numeric; due_v numeric; existing_v numeric; cash_fund numeric:=0; a record; secured_v numeric; general_v numeric; limit_v numeric; reasons jsonb:='[]'::jsonb;
begin
 select * into m from public.members where member_id=p_member_id; if m.member_id is null then raise exception 'Member not found.'; end if;
 months_v:=(extract(year from public.nd_today())::integer-extract(year from m.join_date)::integer)*12+(extract(month from public.nd_today())::integer-extract(month from m.join_date)::integer);
 min_months:=public.nd_num_config('MIN_LOAN_MEMBERSHIP_MONTHS',6); savings_v:=public.nd_member_savings_balance(p_member_id); due_v:=public.nd_current_due_balance(p_member_id); select coalesce(sum(outstanding_principal),0) into existing_v from public.loans where member_id=p_member_id;
 for a in select account_id from public.bank_accounts where status='ACTIVE' loop cash_fund:=cash_fund+greatest(0,coalesce(public.nd_account_balance(a.account_id),0)); end loop;
 secured_v:=round(savings_v*public.nd_num_config('SECURED_LOAN_PERCENT',80)/100,2); general_v:=round(least(savings_v*public.nd_num_config('GENERAL_LOAN_SAVINGS_MULTIPLIER',2),cash_fund*public.nd_num_config('GENERAL_LOAN_FUND_PERCENT',10)/100),2); limit_v:=case when upper(coalesce(p_loan_type,'GENERAL'))='SECURED' then secured_v else general_v end; limit_v:=greatest(0,round(limit_v-existing_v,2));
 if m.status<>'ACTIVE' then reasons:=reasons||jsonb_build_array('সদস্য সক্রিয় নয়'); end if; if months_v<min_months then reasons:=reasons||jsonb_build_array('ন্যূনতম '||min_months||' মাস সদস্যপদ পূর্ণ হয়নি'); end if; if due_v>0 then reasons:=reasons||jsonb_build_array('সঞ্চয়ের বকেয়া আছে'); end if; if limit_v<=0 then reasons:=reasons||jsonb_build_array('ঋণ সীমা উপলব্ধ নেই'); end if;
 return jsonb_build_object('memberId',p_member_id,'membershipMonths',months_v,'minMonths',min_months,'savings',savings_v,'due',round(due_v,2),'existingLoan',existing_v,'securedLimit',secured_v,'generalLimit',general_v,'eligibleLimit',limit_v,'eligible',jsonb_array_length(reasons)=0,'reasons',reasons);
end $$;

create or replace function public.nd_apply_loan(p_user_id text,p_member_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare m public.members; amount_v numeric; loan_type_v text; method_v text; term_v integer; rate_v numeric; elig jsonb; loan_id_v text; g text; seen text[]:=array[]::text[]; now_v timestamptz:=now();
begin
 select * into m from public.members where member_id=p_member_id; if m.member_id is null or m.status<>'ACTIVE' then raise exception 'Active member not found.'; end if; amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Requested amount required.'; end if;
 loan_type_v:=upper(coalesce(nullif(p_payload->>'loanType',''),'GENERAL')); if loan_type_v not in ('GENERAL','SECURED','EMERGENCY','BUSINESS') then raise exception 'Invalid loan type.'; end if; method_v:=upper(coalesce(nullif(p_payload->>'method',''),public.nd_config('DEFAULT_LOAN_METHOD','REDUCING'))); if method_v not in ('REDUCING','FLAT') then raise exception 'Invalid loan calculation method.'; end if; term_v:=coalesce((p_payload->>'termMonths')::integer,12); if term_v<1 or term_v>360 then raise exception 'Loan term must be between 1 and 360 months.'; end if; rate_v:=coalesce((p_payload->>'annualRate')::numeric,public.nd_num_config('DEFAULT_LOAN_ANNUAL_RATE',0)); if rate_v<0 or rate_v>100 then raise exception 'Annual rate must be between 0 and 100.'; end if;
 elig:=public.nd_loan_eligibility(p_member_id,loan_type_v); if coalesce((p_payload->>'enforceEligibility')::boolean,false) and not (elig->>'eligible')::boolean then raise exception 'Loan eligibility requirements are not met: %',elig->'reasons'; end if; if coalesce((p_payload->>'enforceEligibility')::boolean,false) and amount_v>(elig->>'eligibleLimit')::numeric+0.01 then raise exception 'Requested amount exceeds eligible limit: %',elig->>'eligibleLimit'; end if;
 loan_id_v:=public.nd_next_id('LOAN','LN-',7); insert into public.loans(loan_id,member_id,loan_type,application_date,requested_amount,approved_amount,annual_rate,method,term_months,purpose,savings_at_application,eligible_limit,status,approval_status,approved_by,approved_at,disbursed_at,disbursement_txn_id,outstanding_principal,next_due_date,guarantor_required,notes,created_at,created_by,updated_at,updated_by)
 values(loan_id_v,p_member_id,loan_type_v,coalesce(nullif(p_payload->>'applicationDate','')::date,public.nd_today()),amount_v,0,rate_v,method_v,term_v,left(coalesce(p_payload->>'purpose',''),500),(elig->>'savings')::numeric,(elig->>'eligibleLimit')::numeric,'APPLIED','PENDING','',null,null,'',0,null,amount_v>(elig->>'securedLimit')::numeric,left(coalesce(p_payload->>'notes',''),1000),now_v,p_user_id,now_v,p_user_id);
 if jsonb_typeof(p_payload->'guarantors')='array' then for g in select value from jsonb_array_elements_text(p_payload->'guarantors') loop g:=trim(g); if g='' or g=any(seen) then continue; end if; seen:=array_append(seen,g); if g=p_member_id then raise exception 'নিজে নিজের guarantor হতে পারবেন না।'; end if; if not exists(select 1 from public.members where member_id=g and status='ACTIVE') then raise exception 'Guarantor member not found or inactive: %',g; end if; insert into public.guarantors(guarantor_id,loan_id,member_id,guarantor_member_id,status,created_at,created_by) values(public.nd_next_id('GUARANTOR','GUA-',7),loan_id_v,p_member_id,g,'PENDING',now_v,p_user_id); end loop; end if;
 perform public.nd_create_audit(p_user_id,'APPLY','LOAN',loan_id_v,'{}'::jsonb,jsonb_build_object('requested',amount_v,'eligibility',elig),'Loan application'); perform public.nd_create_notification(p_member_id,'LOAN','ঋণ আবেদন গ্রহণ হয়েছে',loan_id_v||' আবেদনটি Pending অবস্থায় আছে।'); return jsonb_build_object('ok',true,'loanId',loan_id_v,'eligibility',elig);
end $$;

create or replace function public.nd_approve_loan(p_user_id text,p_loan_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare l public.loans; approve_v boolean; amount_v numeric; elig jsonb; rate_v numeric; method_v text; term_v integer; note_v text; override_v boolean;
begin
 select * into l from public.loans where loan_id=p_loan_id for update; if l.loan_id is null or l.approval_status<>'PENDING' then raise exception 'Pending loan not found.'; end if; approve_v:=coalesce((p_payload->>'approve')::boolean,true); note_v:=coalesce(p_payload->>'note','');
 if not approve_v then update public.loans set status='REJECTED',approval_status='REJECTED',approved_by=p_user_id,approved_at=now(),notes=coalesce(nullif(note_v,''),notes),updated_at=now(),updated_by=p_user_id where loan_id=p_loan_id; perform public.nd_create_notification(l.member_id,'LOAN','ঋণ আবেদন প্রত্যাখ্যাত',p_loan_id||' আবেদনটি অনুমোদিত হয়নি।'); return jsonb_build_object('ok',true,'status','REJECTED'); end if;
 amount_v:=round(coalesce((p_payload->>'approvedAmount')::numeric,l.requested_amount),2); if amount_v<=0 then raise exception 'Approved amount must be greater than zero.'; end if; elig:=public.nd_loan_eligibility(l.member_id,l.loan_type); override_v:=coalesce((p_payload->>'overrideLimit')::boolean,false); if amount_v>(elig->>'eligibleLimit')::numeric and not override_v then raise exception 'Approved amount exceeds current eligible limit: %',elig->>'eligibleLimit'; end if; if override_v and trim(note_v)='' then raise exception 'Override reason is required.'; end if; rate_v:=coalesce((p_payload->>'annualRate')::numeric,l.annual_rate); if rate_v<0 or rate_v>100 then raise exception 'Annual rate must be between 0 and 100.'; end if; method_v:=upper(coalesce(nullif(p_payload->>'method',''),l.method)); if method_v not in ('REDUCING','FLAT') then raise exception 'Invalid loan calculation method.'; end if; term_v:=coalesce((p_payload->>'termMonths')::integer,l.term_months); if term_v<1 or term_v>360 then raise exception 'Loan term must be between 1 and 360 months.'; end if;
 update public.loans set approved_amount=amount_v,annual_rate=rate_v,method=method_v,term_months=term_v,status='APPROVED',approval_status='APPROVED',approved_by=p_user_id,approved_at=now(),notes=coalesce(nullif(note_v,''),notes),updated_at=now(),updated_by=p_user_id where loan_id=p_loan_id; update public.guarantors set status='APPROVED',approved_at=now() where loan_id=p_loan_id and status='PENDING'; perform public.nd_create_audit(p_user_id,'APPROVE','LOAN',p_loan_id,to_jsonb(l),jsonb_build_object('approvedAmount',amount_v),coalesce(nullif(note_v,''),'Loan approved')); perform public.nd_create_notification(l.member_id,'LOAN','ঋণ অনুমোদিত হয়েছে',p_loan_id||' | '||amount_v||' টাকা অনুমোদিত হয়েছে।'); return jsonb_build_object('ok',true,'status','APPROVED','approvedAmount',amount_v);
end $$;

create or replace function public.nd_generate_loan_schedule(p_loan_id text,p_principal numeric,p_annual_rate numeric,p_method text,p_months integer,p_disbursement_date date)
returns integer language plpgsql security definer set search_path=public as $$
declare opening_v numeric:=round(p_principal,2); monthly_rate numeric:=coalesce(p_annual_rate,0)/12/100; emi numeric; flat_profit numeric; profit_v numeric; principal_v numeric; total_v numeric; i integer; due_v date;
begin
 if exists(select 1 from public.loan_schedule where loan_id=p_loan_id) then raise exception 'Loan schedule already exists.'; end if; p_months:=greatest(1,p_months); p_method:=upper(coalesce(p_method,'REDUCING')); if monthly_rate=0 then emi:=p_principal/p_months; else emi:=(p_principal*monthly_rate*power(1+monthly_rate,p_months))/(power(1+monthly_rate,p_months)-1); end if; flat_profit:=p_principal*(coalesce(p_annual_rate,0)/100)*(p_months/12.0);
 for i in 1..p_months loop
   if p_method='FLAT' then principal_v:=p_principal/p_months; profit_v:=flat_profit/p_months; else profit_v:=opening_v*monthly_rate; principal_v:=emi-profit_v; if i=p_months then principal_v:=opening_v; end if; end if;
   principal_v:=round(principal_v,2); profit_v:=round(profit_v,2); total_v:=round(principal_v+profit_v,2); due_v:=(p_disbursement_date+(i||' months')::interval)::date;
   insert into public.loan_schedule(schedule_id,loan_id,installment_no,due_date,opening_principal,principal_due,profit_due,total_due,principal_paid,profit_paid,penalty_paid,status,paid_at)
   values(public.nd_next_id('LOAN_SCHEDULE','SCH-',8),p_loan_id,i,due_v,round(opening_v,2),principal_v,profit_v,total_v,0,0,0,'DUE',null); opening_v:=round(greatest(0,opening_v-principal_v),2);
 end loop; return p_months;
end $$;

create or replace function public.nd_disburse_loan(p_user_id text,p_loan_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare l public.loans; account public.bank_accounts; amount_v numeric; date_v date; txn_id_v text; next_v date; recv public.chart_of_accounts; bal numeric;
begin
 select * into l from public.loans where loan_id=p_loan_id for update; if l.loan_id is null or l.approval_status<>'APPROVED' or l.status<>'APPROVED' then raise exception 'Approved loan not ready for disbursement.'; end if; amount_v:=round(l.approved_amount,2); if amount_v<=0 then raise exception 'Approved amount is invalid.'; end if; select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-BANK') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; bal:=public.nd_account_balance(account.account_id); if amount_v>bal+0.01 then raise exception 'Loan disbursement exceeds available % balance: %',account.account_name,bal; end if; date_v:=coalesce(nullif(p_payload->>'date','')::date,public.nd_today()); txn_id_v:=public.nd_next_id('TXN','TRX-',8);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by)
 values(txn_id_v,date_v,l.member_id,'LOAN_DISBURSEMENT','LOAN','Loan disbursement '||p_loan_id,'DEBIT',amount_v,amount_v,0,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),coalesce(p_payload->>'reference',''),p_loan_id,'','POSTED','','',now(),p_user_id,now(),p_user_id);
 recv:=public.nd_coa_by_system('LOAN_RECEIVABLE'); perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',recv.account_code,'debit',amount_v,'credit',0),jsonb_build_object('accountCode',account.account_code,'debit',0,'credit',amount_v)),l.member_id,p_loan_id,'Loan disbursement '||p_loan_id); perform public.nd_generate_loan_schedule(p_loan_id,amount_v,l.annual_rate,l.method,l.term_months,date_v); select due_date into next_v from public.loan_schedule where loan_id=p_loan_id order by due_date limit 1; update public.loans set status='ACTIVE',disbursed_at=date_v,disbursement_txn_id=txn_id_v,outstanding_principal=amount_v,next_due_date=next_v,updated_at=now(),updated_by=p_user_id where loan_id=p_loan_id; perform public.nd_create_audit(p_user_id,'DISBURSE','LOAN',p_loan_id,to_jsonb(l),(select to_jsonb(t) from public.transactions t where txn_id=txn_id_v),'Loan disbursed'); perform public.nd_create_notification(l.member_id,'LOAN','ঋণ বিতরণ হয়েছে',p_loan_id||' | '||amount_v||' টাকা বিতরণ হয়েছে।'); return jsonb_build_object('ok',true,'txnId',txn_id_v,'loanId',p_loan_id,'nextDueDate',next_v);
end $$;

create or replace function public.nd_refresh_loan_status(p_loan_id text,p_user_id text default 'SYSTEM')
returns text language plpgsql security definer set search_path=public as $$
declare outstanding numeric; next_v date; status_v text;
begin
 select round(coalesce(sum(greatest(0,principal_due-principal_paid)),0),2) into outstanding from public.loan_schedule where loan_id=p_loan_id; select due_date into next_v from public.loan_schedule where loan_id=p_loan_id and status<>'PAID' order by due_date limit 1; status_v:=case when outstanding<=0 then 'CLOSED' when next_v is not null and next_v<public.nd_today() then 'OVERDUE' else 'ACTIVE' end; update public.loans set outstanding_principal=outstanding,next_due_date=next_v,status=status_v,updated_at=now(),updated_by=p_user_id where loan_id=p_loan_id; return status_v;
end $$;

create or replace function public.nd_collect_loan_payment(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare l public.loans; amount_v numeric; remain_sched numeric; account public.bank_accounts; date_v date; payment_id_v text; txn_id_v text; receipt_id_v text; remaining numeric; total_principal numeric:=0; total_profit numeric:=0; total_penalty numeric:=0; s public.loan_schedule; profit_rem numeric; principal_rem numeric; pay_profit numeric; pay_principal numeric; np numeric; ni numeric; paid_v boolean; lines jsonb; alloc_id_v text;
begin
 select * into l from public.loans where loan_id=p_payload->>'loanId' for update; if l.loan_id is null or l.status not in ('ACTIVE','OVERDUE') then raise exception 'Active loan not found.'; end if; amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Payment amount required.'; end if;
 select coalesce(sum(greatest(0,principal_due-principal_paid)+greatest(0,profit_due-profit_paid)),0) into remain_sched from public.loan_schedule where loan_id=l.loan_id and status<>'PAID'; if amount_v>remain_sched+0.01 then raise exception 'Payment exceeds remaining scheduled amount: %',round(remain_sched,2); end if; select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-CASH') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; date_v:=coalesce(nullif(p_payload->>'date','')::date,public.nd_today()); payment_id_v:=public.nd_next_id('LOAN_PAYMENT','LP-',8); txn_id_v:=public.nd_next_id('TXN','TRX-',8); receipt_id_v:=public.nd_next_receipt_id(); remaining:=amount_v;
 for s in select * from public.loan_schedule where loan_id=l.loan_id and status<>'PAID' order by installment_no for update loop exit when remaining<=0.001; profit_rem:=greatest(0,s.profit_due-s.profit_paid); principal_rem:=greatest(0,s.principal_due-s.principal_paid); pay_profit:=least(remaining,profit_rem); remaining:=round(remaining-pay_profit,2); pay_principal:=least(remaining,principal_rem); remaining:=round(remaining-pay_principal,2); total_profit:=total_profit+pay_profit; total_principal:=total_principal+pay_principal; np:=round(s.principal_paid+pay_principal,2); ni:=round(s.profit_paid+pay_profit,2); paid_v:=np+0.01>=s.principal_due and ni+0.01>=s.profit_due; update public.loan_schedule set principal_paid=np,profit_paid=ni,status=case when paid_v then 'PAID' else 'PARTIAL' end,paid_at=case when paid_v then date_v else null end where schedule_id=s.schedule_id; alloc_id_v:=public.nd_next_id('ALLOC','ALC-',9); insert into public.loan_payment_allocations(alloc_id,payment_id,schedule_id,principal_amount,profit_amount,penalty_amount,created_at) values(alloc_id_v,payment_id_v,s.schedule_id,round(pay_principal,2),round(pay_profit,2),0,now()); end loop;
 total_principal:=round(total_principal,2); total_profit:=round(total_profit,2);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by)
 values(txn_id_v,date_v,l.member_id,'LOAN_PAYMENT','LOAN','Loan payment '||l.loan_id,'CREDIT',amount_v,total_principal,total_profit,total_penalty,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),coalesce(p_payload->>'reference',''),l.loan_id,receipt_id_v,'POSTED','','',now(),p_user_id,now(),p_user_id);
 insert into public.loan_payments(payment_id,loan_id,member_id,txn_id,payment_date,amount,principal_amount,profit_amount,penalty_amount,receipt_id,created_at,created_by) values(payment_id_v,l.loan_id,l.member_id,txn_id_v,date_v,amount_v,total_principal,total_profit,total_penalty,receipt_id_v,now(),p_user_id); insert into public.receipts(receipt_id,txn_id,member_id,receipt_date,amount,purpose,payment_method,reference,status,print_count,created_at,created_by) values(receipt_id_v,txn_id_v,l.member_id,date_v,amount_v,'ঋণ কিস্তি '||l.loan_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),coalesce(p_payload->>'reference',''),'ACTIVE',0,now(),p_user_id);
 lines:=jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',amount_v,'credit',0)); if total_principal>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('LOAN_RECEIVABLE')).account_code,'debit',0,'credit',total_principal)); end if; if total_profit>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('LOAN_INCOME')).account_code,'debit',0,'credit',total_profit)); end if; if total_penalty>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('LATE_FEE_INCOME')).account_code,'debit',0,'credit',total_penalty)); end if; perform public.nd_post_journal(p_user_id,txn_id_v,date_v,lines,l.member_id,l.loan_id,'Loan payment '||l.loan_id); perform public.nd_refresh_loan_status(l.loan_id,p_user_id); perform public.nd_create_audit(p_user_id,'PAYMENT','LOAN',l.loan_id,'{}'::jsonb,(select to_jsonb(t) from public.transactions t where txn_id=txn_id_v),'Loan installment'); perform public.nd_create_notification(l.member_id,'LOAN_PAYMENT','ঋণ কিস্তি জমা হয়েছে',receipt_id_v||' | '||amount_v||' টাকা কিস্তি জমা হয়েছে।'); return jsonb_build_object('ok',true,'paymentId',payment_id_v,'txnId',txn_id_v,'receiptId',receipt_id_v,'principal',total_principal,'profit',total_profit);
end $$;

create or replace function public.nd_create_income(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare amount_v numeric; account public.bank_accounts; category_v text; income_type_v text; income_sys text; income_coa public.chart_of_accounts; txn_id_v text; income_id_v text; voucher_id_v text; date_v date; description_v text; reference_v text; note_v text; client_v text;
begin
 amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Amount required.'; end if; client_v:=left(trim(coalesce(p_payload->>'clientRequestId','')),120); if client_v<>'' and exists(select 1 from public.income where client_request_id=client_v) then return (select jsonb_build_object('ok',true,'duplicate',true,'incomeId',income_id,'txnId',txn_id,'voucherId',voucher_id,'profitId',profit_id,'incomeType',income_type) from public.income where client_request_id=client_v limit 1); end if; select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-CASH') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; category_v:=upper(left(trim(coalesce(p_payload->>'category','OTHER')),100)); income_type_v:=upper(coalesce(nullif(p_payload->>'incomeType',''),'GENERAL')); income_sys:=coalesce(nullif(p_payload->>'systemIncomeAccount',''),case category_v when 'LATE_FEE' then 'LATE_FEE_INCOME' when 'INVESTMENT_INCOME' then 'INVESTMENT_INCOME' else 'OTHER_INCOME' end); income_coa:=public.nd_coa_by_system(income_sys); txn_id_v:=public.nd_next_id('TXN','TRX-',8); income_id_v:=public.nd_next_id('INCOME','INC-',7); voucher_id_v:=public.nd_next_voucher_id(); date_v:=coalesce(nullif(p_payload->>'date','')::date,public.nd_today()); description_v:=left(trim(coalesce(p_payload->>'description',category_v,'Other income')),1000); reference_v:=left(trim(coalesce(p_payload->>'reference','')),300); note_v:=left(trim(coalesce(p_payload->>'note',p_payload->>'notes','')),2000);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by,note_purpose) values(txn_id_v,date_v,coalesce(p_payload->>'memberId',''),'INCOME','INCOME',description_v,'CREDIT',amount_v,0,amount_v,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),reference_v,income_id_v,'','POSTED','','',now(),p_user_id,now(),p_user_id,note_v);
 insert into public.income(income_id,date,category,amount,account_id,reference,description,txn_id,status,created_at,created_by,income_type,profit_id,voucher_id,client_request_id,note,updated_at,updated_by) values(income_id_v,date_v,category_v,amount_v,account.account_id,reference_v,description_v,txn_id_v,'POSTED',now(),p_user_id,income_type_v,'',voucher_id_v,client_v,note_v,now(),p_user_id); insert into public.vouchers(voucher_id,txn_id,date,type,payee,member_id,amount,purpose,account_id,reference,status,created_at,created_by) values(voucher_id_v,txn_id_v,date_v,'INCOME',coalesce(p_payload->>'payee',p_payload->>'source','Income Source'),coalesce(p_payload->>'memberId',''),amount_v,description_v,account.account_id,reference_v,'POSTED',now(),p_user_id); perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',amount_v,'credit',0),jsonb_build_object('accountCode',income_coa.account_code,'debit',0,'credit',amount_v)),coalesce(p_payload->>'memberId',''),income_id_v,description_v); perform public.nd_create_audit(p_user_id,'CREATE','INCOME',income_id_v,'{}'::jsonb,jsonb_build_object('txnId',txn_id_v,'voucherId',voucher_id_v),'General income posted'); return jsonb_build_object('ok',true,'duplicate',false,'incomeId',income_id_v,'txnId',txn_id_v,'voucherId',voucher_id_v,'profitId','','incomeType',income_type_v);
end $$;

create or replace function public.nd_create_expense(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare amount_v numeric; account public.bank_accounts; expense_coa public.chart_of_accounts; txn_id_v text; expense_id_v text; voucher_id_v text; date_v date; description_v text; reference_v text; client_v text; bal numeric;
begin
 amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Amount required.'; end if; client_v:=left(trim(coalesce(p_payload->>'clientRequestId','')),120); if client_v<>'' and exists(select 1 from public.expenses where client_request_id=client_v) then return (select jsonb_build_object('ok',true,'duplicate',true,'expenseId',expense_id,'txnId',txn_id,'voucherId',voucher_id,'allocationMethod',allocation_method) from public.expenses where client_request_id=client_v limit 1); end if; select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-CASH') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; bal:=public.nd_account_balance(account.account_id); if amount_v>bal+0.01 then raise exception 'Expense exceeds available % balance: %',account.account_name,bal; end if; expense_coa:=public.nd_coa_by_system(coalesce(nullif(p_payload->>'systemExpenseAccount',''),'OPERATING_EXPENSE')); txn_id_v:=public.nd_next_id('TXN','TRX-',8); expense_id_v:=public.nd_next_id('EXPENSE','EXP-',7); voucher_id_v:=public.nd_next_voucher_id(); date_v:=coalesce(nullif(p_payload->>'date','')::date,public.nd_today()); description_v:=left(trim(coalesce(p_payload->>'description',p_payload->>'category','Expense')),1000); reference_v:=left(trim(coalesce(p_payload->>'reference','')),300);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by) values(txn_id_v,date_v,'','EXPENSE','EXPENSE',description_v,'DEBIT',amount_v,0,0,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),reference_v,expense_id_v,'','POSTED','','',now(),p_user_id,now(),p_user_id);
 insert into public.expenses(expense_id,date,category,amount,account_id,reference,description,document_file_id,txn_id,status,approval_status,created_at,created_by,updated_at,updated_by,allocation_method,total_units,member_count,allocated_amount,voucher_id,client_request_id,allocation_status) values(expense_id_v,date_v,coalesce(p_payload->>'category','OPERATING'),amount_v,account.account_id,reference_v,description_v,'',txn_id_v,'POSTED','APPROVED',now(),p_user_id,now(),p_user_id,'NONE',0,0,0,voucher_id_v,client_v,'NOT_APPLICABLE'); insert into public.vouchers(voucher_id,txn_id,date,type,payee,member_id,amount,purpose,account_id,reference,status,created_at,created_by) values(voucher_id_v,txn_id_v,date_v,'EXPENSE',coalesce(p_payload->>'payee',p_payload->>'vendor','Expense Payee'),'',amount_v,description_v,account.account_id,reference_v,'POSTED',now(),p_user_id); perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',expense_coa.account_code,'debit',amount_v,'credit',0),jsonb_build_object('accountCode',account.account_code,'debit',0,'credit',amount_v)),'',expense_id_v,description_v); perform public.nd_create_audit(p_user_id,'CREATE','EXPENSE',expense_id_v,'{}'::jsonb,jsonb_build_object('txnId',txn_id_v,'voucherId',voucher_id_v),'Expense posted'); return jsonb_build_object('ok',true,'duplicate',false,'expenseId',expense_id_v,'txnId',txn_id_v,'voucherId',voucher_id_v,'allocationMethod','NONE');
end $$;
