-- Investment and profit-management rules ported from v1.1.6.

create or replace function public.nd_ensure_profit_source_for_investment(p_user_id text,p_investment_id text,p_name text,p_category text)
returns public.profit_sources language plpgsql security definer set search_path=public as $$
declare r public.profit_sources; id text;
begin
 select * into r from public.profit_sources where investment_id=p_investment_id and status<>'INACTIVE' limit 1 for update;
 if r.source_id is not null then update public.profit_sources set source_name=coalesce(nullif(p_name,''),source_name),category=upper(coalesce(nullif(p_category,''),category,'OTHER')),updated_at=now(),updated_by=coalesce(p_user_id,'SYSTEM') where source_id=r.source_id returning * into r; return r; end if;
 id:=public.nd_next_id('PROFIT_SOURCE','PSR-',6); insert into public.profit_sources(source_id,source_name,category,investment_id,project_reference,description,status,created_at,created_by,updated_at,updated_by) values(id,coalesce(nullif(p_name,''),p_investment_id),upper(coalesce(nullif(p_category,''),'OTHER')),coalesce(p_investment_id,''),'','Investment-linked profit source','ACTIVE',now(),coalesce(p_user_id,'SYSTEM'),now(),coalesce(p_user_id,'SYSTEM')) returning * into r; return r;
end $$;

create or replace function public.nd_profit_period(p_payload jsonb)
returns jsonb language plpgsql stable as $$
declare type_v text:=upper(coalesce(nullif(p_payload->>'periodType',''),'CUSTOM')); year_v text:=coalesce(nullif(p_payload->>'year',''),nullif(p_payload->>'financialYear',''),to_char(public.nd_today(),'YYYY')); start_v date; end_v date; label_v text; month_v text; q integer; h integer; sm integer; em integer;
begin
 if type_v='MONTHLY' then month_v:=left(coalesce(nullif(p_payload->>'month',''),nullif(p_payload->>'periodStart',''),to_char(public.nd_today(),'YYYY-MM')),7); if month_v!~'^\d{4}-\d{2}$' then raise exception 'Monthly period must be YYYY-MM.'; end if; start_v:=(month_v||'-01')::date; end_v:=(start_v+interval '1 month - 1 day')::date; label_v:=month_v;
 elsif type_v='QUARTERLY' then q:=greatest(1,least(4,coalesce((p_payload->>'quarter')::integer,1))); sm:=(q-1)*3+1; em:=sm+2; start_v:=make_date(year_v::integer,sm,1); end_v:=(make_date(year_v::integer,em,1)+interval '1 month - 1 day')::date; label_v:=year_v||' Q'||q;
 elsif type_v='HALF_YEARLY' then h:=greatest(1,least(2,coalesce((p_payload->>'half')::integer,1))); sm:=case when h=1 then 1 else 7 end; em:=case when h=1 then 6 else 12 end; start_v:=make_date(year_v::integer,sm,1); end_v:=(make_date(year_v::integer,em,1)+interval '1 month - 1 day')::date; label_v:=year_v||' H'||h;
 elsif type_v='YEARLY' then start_v:=make_date(year_v::integer,1,1); end_v:=make_date(year_v::integer,12,31); label_v:=year_v;
 else type_v:='CUSTOM'; start_v:=coalesce(nullif(p_payload->>'periodStart','')::date,nullif(p_payload->>'profitDate','')::date,public.nd_today()); end_v:=coalesce(nullif(p_payload->>'periodEnd','')::date,nullif(p_payload->>'profitDate','')::date,start_v); if start_v>end_v then raise exception 'Valid custom start/end dates required.'; end if; label_v:=case when start_v=end_v then start_v::text else start_v||' to '||end_v end;
 end if;
 return jsonb_build_object('type',type_v,'start',start_v,'end',end_v,'label',label_v,'financialYear',to_char(start_v,'YYYY'));
end $$;

create or replace function public.nd_create_profit_record_core(p_user_id text,p_payload jsonb)
returns text language plpgsql security definer set search_path=public as $$
declare source public.profit_sources; period jsonb; amount_v numeric; id text; profit_date_v date;
begin
 select * into source from public.profit_sources where source_id=p_payload->>'sourceId'; if source.source_id is null then raise exception 'Profit source not found.'; end if; period:=public.nd_profit_period(p_payload); amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Profit amount required.'; end if; id:=public.nd_next_id('PROFIT','PRF-',8); profit_date_v:=coalesce(nullif(p_payload->>'profitDate','')::date,(period->>'end')::date);
 insert into public.profit_records(profit_id,source_id,investment_id,category,profit_date,period_type,period_start,period_end,period_label,amount,distributed_amount,undistributed_amount,status,source_txn_id,reference,notes,created_at,created_by,updated_at,updated_by,source_income_id,source_voucher_id)
 values(id,source.source_id,coalesce(nullif(p_payload->>'investmentId',''),source.investment_id,''),upper(coalesce(nullif(p_payload->>'category',''),source.category,'OTHER')),profit_date_v,period->>'type',(period->>'start')::date,(period->>'end')::date,period->>'label',amount_v,0,amount_v,'ACTIVE',coalesce(p_payload->>'sourceTxnId',''),coalesce(p_payload->>'reference',''),coalesce(p_payload->>'notes',''),now(),coalesce(p_user_id,'SYSTEM'),now(),coalesce(p_user_id,'SYSTEM'),coalesce(p_payload->>'sourceIncomeId',''),coalesce(p_payload->>'sourceVoucherId',''));
 return id;
end $$;

create or replace function public.nd_profit_approved_amount(p_profit_id text)
returns numeric language sql stable as $$
 select round(coalesce(sum(d.amount),0),2) from public.profit_distribution d left join public.transactions t on t.txn_id=d.txn_id where d.profit_id=p_profit_id and d.status='APPROVED' and (t.txn_id is null or t.status in ('POSTED','CORRECTED','REVERSED'))
$$;

create or replace function public.nd_distribution_approved_amount(p_distribution_id text)
returns numeric language sql stable as $$ select round(coalesce(sum(amount),0),2) from public.profit_distribution where distribution_id=p_distribution_id and status='APPROVED' $$;

create or replace function public.nd_profit_reserved_amount(p_profit_id text)
returns numeric language sql stable as $$
 select round(public.nd_profit_approved_amount(p_profit_id)+coalesce((select sum(greatest(0,requested_amount-public.nd_distribution_approved_amount(distribution_id))) from public.profit_distributions where profit_id=p_profit_id and status in ('DRAFT','PROCESSING')),0),2)
$$;

create or replace function public.nd_refresh_profit_record(p_profit_id text,p_user_id text default 'SYSTEM')
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.profit_records; dist numeric; rem numeric; st text;
begin
 select * into p from public.profit_records where profit_id=p_profit_id for update; if p.profit_id is null then return null; end if; if p.status in ('REVERSED','CANCELLED') then return to_jsonb(p); end if; dist:=public.nd_profit_approved_amount(p_profit_id); rem:=round(greatest(0,p.amount-dist),2); st:=case when rem<=0.009 then 'FULLY_DISTRIBUTED' when dist>0 then 'PARTIALLY_DISTRIBUTED' else 'ACTIVE' end; update public.profit_records set distributed_amount=dist,undistributed_amount=rem,status=st,updated_at=now(),updated_by=p_user_id where profit_id=p_profit_id returning * into p; return to_jsonb(p);
end $$;

create or replace function public.nd_refresh_investment_summary(p_investment_id text,p_user_id text default 'SYSTEM')
returns jsonb language plpgsql security definer set search_path=public as $$
declare inv public.investments; cost numeric; principal numeric; profit_returns numeric; closure public.investment_closures; st text; profit_v numeric; loss_v numeric:=0;
begin
 select * into inv from public.investments where investment_id=p_investment_id for update; if inv.investment_id is null then return null; end if; cost:=round(coalesce(nullif(inv.total_invested,0),inv.amount),2); select round(coalesce(sum(amount),0),2) into principal from public.investment_returns where investment_id=p_investment_id and type='PRINCIPAL' and status='POSTED'; select round(coalesce(sum(amount),0),2) into profit_returns from public.investment_returns where investment_id=p_investment_id and type='PROFIT' and status='POSTED'; select * into closure from public.investment_closures where investment_id=p_investment_id and status='POSTED' order by created_at desc limit 1; profit_v:=profit_returns;
 if closure.closure_id is not null then principal:=closure.principal_returned; profit_v:=round(profit_v+closure.profit_amount,2); loss_v:=closure.loss_amount; st:=case when upper(inv.status)='COMPLETED' then 'COMPLETED' else 'SOLD_CLOSED' end;
 elsif upper(coalesce(inv.status,''))='CANCELLED' then st:='CANCELLED'; elsif principal+0.01>=cost then st:=case when upper(inv.status)='COMPLETED' then 'COMPLETED' else 'PRINCIPAL_RETURNED' end; elsif principal>0 then st:='PARTIALLY_RETURNED'; else st:='ACTIVE'; end if;
 update public.investments set total_invested=cost,principal_returned=round(principal,2),profit_generated=round(profit_v,2),loss_generated=round(loss_v,2),status=st,updated_at=now(),updated_by=p_user_id where investment_id=p_investment_id returning * into inv; return to_jsonb(inv);
end $$;

create or replace function public.nd_create_investment(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare name_v text; amount_v numeric; total_v numeric; account public.bank_accounts; bal numeric; id text; date_v date; txn_id_v text; source public.profit_sources;
begin
 name_v:=trim(coalesce(p_payload->>'name','')); if name_v='' then raise exception 'Investment name required.'; end if; amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); total_v:=round(coalesce((p_payload->>'totalInvested')::numeric,amount_v),2); if amount_v<=0 or total_v<=0 then raise exception 'Investment amount required.'; end if; if total_v+0.01<amount_v then raise exception 'Total invested cannot be lower than original principal.'; end if; select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-BANK') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; bal:=public.nd_account_balance(account.account_id); if total_v>bal+0.01 then raise exception 'Investment purchase exceeds available % balance: %',account.account_name,bal; end if; id:=public.nd_next_id('INVESTMENT','INV-',7); date_v:=coalesce(nullif(p_payload->>'startDate','')::date,public.nd_today()); txn_id_v:=public.nd_next_id('TXN','TRX-',8);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by) values(txn_id_v,date_v,'','INVESTMENT_PURCHASE','INVESTMENT','Investment: '||name_v,'DEBIT',total_v,total_v,0,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),coalesce(p_payload->>'reference',''),id,'','POSTED',coalesce(p_payload->>'parentTxnId',''),coalesce(p_payload->>'reason',''),now(),p_user_id,now(),p_user_id);
 perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('INVESTMENT_ASSET')).account_code,'debit',total_v,'credit',0),jsonb_build_object('accountCode',account.account_code,'debit',0,'credit',total_v)),'',id,'Investment: '||name_v);
 insert into public.investments(investment_id,type,name,start_date,amount,expected_return_rate,expected_end_date,status,location,land_size,mouza,dag,khatian,partner,ownership_percent,responsible_person,document_folder_id,purchase_txn_id,notes,created_at,created_by,updated_at,updated_by,total_invested,principal_returned,closure_id,closed_at,selling_amount,profit_generated,loss_generated,closing_reference,close_notes,closed_by)
 values(id,upper(coalesce(nullif(p_payload->>'type',''),'OTHER')),name_v,date_v,amount_v,coalesce((p_payload->>'expectedReturnRate')::numeric,0),nullif(p_payload->>'expectedEndDate','')::date,'ACTIVE',coalesce(p_payload->>'location',''),coalesce((p_payload->>'landSize')::numeric,0),coalesce(p_payload->>'mouza',''),coalesce(p_payload->>'dag',''),coalesce(p_payload->>'khatian',''),coalesce(p_payload->>'partner',''),coalesce((p_payload->>'ownershipPercent')::numeric,0),coalesce(p_payload->>'responsiblePerson',''),'',''||txn_id_v,coalesce(p_payload->>'notes',''),now(),p_user_id,now(),p_user_id,total_v,0,'',null,0,0,0,'','',''); source:=public.nd_ensure_profit_source_for_investment(p_user_id,id,name_v,upper(coalesce(nullif(p_payload->>'type',''),'OTHER'))); perform public.nd_create_audit(p_user_id,'CREATE','INVESTMENT',id,'{}'::jsonb,p_payload,'Investment created'); return jsonb_build_object('ok',true,'investmentId',id,'txnId',txn_id_v,'sourceId',source.source_id);
end $$;

create or replace function public.nd_record_investment_return(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare inv public.investments; amount_v numeric; type_v text; remaining_v numeric; account public.bank_accounts; date_v date; rid text; txn_id_v text; source public.profit_sources; profit_id_v text:=''; refreshed jsonb; credit_code text;
begin
 amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); type_v:=upper(coalesce(nullif(p_payload->>'type',''),'PROFIT')); if amount_v<=0 then raise exception 'Amount required.'; end if; if type_v not in ('PROFIT','PRINCIPAL') then raise exception 'Return type must be PROFIT or PRINCIPAL.'; end if; select * into inv from public.investments where investment_id=p_payload->>'investmentId' for update; if inv.investment_id is null then raise exception 'Investment not found.'; end if; if upper(inv.status) not in ('ACTIVE','PARTIALLY_RETURNED','PRINCIPAL_RETURNED') then raise exception 'Only an open investment can receive a return.'; end if; if type_v='PRINCIPAL' then select round(coalesce(sum(amount),0),2) into remaining_v from public.investment_returns where investment_id=inv.investment_id and type='PRINCIPAL' and status='POSTED'; remaining_v:=round(coalesce(nullif(inv.total_invested,0),inv.amount)-remaining_v,2); if amount_v>remaining_v+0.01 then raise exception 'Principal return exceeds remaining principal: %',remaining_v; end if; end if; select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-BANK') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; date_v:=coalesce(nullif(p_payload->>'date','')::date,public.nd_today()); rid:=public.nd_next_id('INV_RETURN','RET-',7); txn_id_v:=public.nd_next_id('TXN','TRX-',8);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by) values(txn_id_v,date_v,'','INVESTMENT_RETURN_'||type_v,'INVESTMENT',case when type_v='PROFIT' then 'Investment profit: ' else 'Investment principal return: ' end||inv.name,'CREDIT',amount_v,case when type_v='PRINCIPAL' then amount_v else 0 end,case when type_v='PROFIT' then amount_v else 0 end,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),coalesce(p_payload->>'reference',''),inv.investment_id,'','POSTED',coalesce(p_payload->>'parentTxnId',''),coalesce(p_payload->>'reason',''),now(),p_user_id,now(),p_user_id);
 source:=public.nd_ensure_profit_source_for_investment(p_user_id,inv.investment_id,inv.name,inv.type); if type_v='PROFIT' then profit_id_v:=public.nd_create_profit_record_core(p_user_id,p_payload||jsonb_build_object('sourceId',source.source_id,'investmentId',inv.investment_id,'category',inv.type,'profitDate',date_v,'amount',amount_v,'sourceTxnId',txn_id_v,'periodType',coalesce(nullif(p_payload->>'periodType',''),'CUSTOM'),'periodStart',coalesce(nullif(p_payload->>'periodStart',''),date_v::text),'periodEnd',coalesce(nullif(p_payload->>'periodEnd',''),date_v::text))); end if;
 insert into public.investment_returns(return_id,investment_id,return_date,type,amount,txn_id,notes,created_at,created_by,status,parent_return_id,updated_at,updated_by,profit_id) values(rid,inv.investment_id,date_v,type_v,amount_v,txn_id_v,coalesce(p_payload->>'notes',''),now(),p_user_id,'POSTED',coalesce(p_payload->>'parentReturnId',''),now(),p_user_id,profit_id_v); credit_code:=case when type_v='PROFIT' then (public.nd_coa_by_system('INVESTMENT_INCOME')).account_code else (public.nd_coa_by_system('INVESTMENT_ASSET')).account_code end; perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',amount_v,'credit',0),jsonb_build_object('accountCode',credit_code,'debit',0,'credit',amount_v)),'',inv.investment_id,case when type_v='PROFIT' then 'Investment profit: ' else 'Investment principal return: ' end||inv.name); refreshed:=public.nd_refresh_investment_summary(inv.investment_id,p_user_id); if type_v='PRINCIPAL' and coalesce((p_payload->>'markCompleted')::boolean,false) and (refreshed->>'principal_returned')::numeric+0.01>=coalesce((refreshed->>'total_invested')::numeric,(refreshed->>'amount')::numeric) then update public.investments set status='COMPLETED',updated_at=now(),updated_by=p_user_id where investment_id=inv.investment_id; refreshed:=public.nd_refresh_investment_summary(inv.investment_id,p_user_id); end if; perform public.nd_create_audit(p_user_id,'RETURN','INVESTMENT_RETURN',rid,'{}'::jsonb,(select to_jsonb(t) from public.transactions t where txn_id=txn_id_v),coalesce(nullif(p_payload->>'reason',''),'Investment return')); return jsonb_build_object('ok',true,'returnId',rid,'txnId',txn_id_v,'profitId',profit_id_v,'status',refreshed->>'status');
end $$;

create or replace function public.nd_close_investment(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare inv public.investments; cost numeric; previous_principal numeric; selling numeric; cash numeric; remaining_asset numeric; profit_v numeric; loss_v numeric; principal_now numeric; principal_total numeric; date_v date; account public.bank_accounts; closure_id_v text; txn_id_v text; reference_v text; lines jsonb:='[]'::jsonb; source public.profit_sources; profit_id_v text:=''; final_status text;
begin
 select * into inv from public.investments where investment_id=p_payload->>'investmentId' for update; if inv.investment_id is null then raise exception 'Investment not found.'; end if; if upper(inv.status) not in ('ACTIVE','PARTIALLY_RETURNED','PRINCIPAL_RETURNED') then raise exception 'Investment is already closed, completed or cancelled.'; end if; if exists(select 1 from public.investment_closures where investment_id=inv.investment_id and status='POSTED') then raise exception 'This investment has already been closed.'; end if; cost:=round(coalesce(nullif(inv.total_invested,0),inv.amount),2); select round(coalesce(sum(amount),0),2) into previous_principal from public.investment_returns where investment_id=inv.investment_id and type='PRINCIPAL' and status='POSTED'; selling:=round(coalesce((p_payload->>'sellingAmount')::numeric,0),2); if selling<0 then raise exception 'Selling amount cannot be negative.'; end if; if selling+0.01<previous_principal then raise exception 'Selling amount cannot be lower than principal already returned (%).',previous_principal; end if; cash:=round(selling-previous_principal,2); remaining_asset:=round(greatest(0,cost-previous_principal),2); profit_v:=round(greatest(0,selling-cost),2); loss_v:=round(greatest(0,cost-selling),2); principal_now:=round(least(cash,remaining_asset),2); principal_total:=round(previous_principal+principal_now,2); date_v:=coalesce(nullif(p_payload->>'closeDate','')::date,public.nd_today()); select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-BANK') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; closure_id_v:=public.nd_next_id('INV_CLOSURE','CLS-',7); txn_id_v:=public.nd_next_id('TXN','TRX-',8); reference_v:=coalesce(nullif(p_payload->>'reference',''),closure_id_v);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by) values(txn_id_v,date_v,'','INVESTMENT_CLOSURE','INVESTMENT','Investment closed/sold: '||inv.name,'CREDIT',cash,principal_now,profit_v,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),reference_v,closure_id_v,'','POSTED','','',now(),p_user_id,now(),p_user_id);
 if cash>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',cash,'credit',0)); end if; if loss_v>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('INVESTMENT_LOSS')).account_code,'debit',loss_v,'credit',0)); end if; if remaining_asset>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('INVESTMENT_ASSET')).account_code,'debit',0,'credit',remaining_asset)); end if; if profit_v>0 then lines:=lines||jsonb_build_array(jsonb_build_object('accountCode',(public.nd_coa_by_system('INVESTMENT_INCOME')).account_code,'debit',0,'credit',profit_v)); end if; if jsonb_array_length(lines)>0 then perform public.nd_post_journal(p_user_id,txn_id_v,date_v,lines,'',inv.investment_id,'Investment closed/sold: '||inv.name); end if;
 source:=public.nd_ensure_profit_source_for_investment(p_user_id,inv.investment_id,inv.name,inv.type); if profit_v>0 then profit_id_v:=public.nd_create_profit_record_core(p_user_id,p_payload||jsonb_build_object('sourceId',source.source_id,'investmentId',inv.investment_id,'category',inv.type,'profitDate',date_v,'amount',profit_v,'sourceTxnId',txn_id_v,'reference',reference_v,'periodType',coalesce(nullif(p_payload->>'periodType',''),'CUSTOM'),'periodStart',coalesce(nullif(p_payload->>'periodStart',''),date_v::text),'periodEnd',coalesce(nullif(p_payload->>'periodEnd',''),date_v::text))); end if;
 insert into public.investment_closures(closure_id,investment_id,close_date,selling_amount,cash_received,total_cost,principal_returned,profit_amount,loss_amount,account_id,txn_id,profit_id,reference,notes,status,parent_closure_id,created_at,created_by,updated_at,updated_by) values(closure_id_v,inv.investment_id,date_v,selling,cash,cost,principal_total,profit_v,loss_v,account.account_id,txn_id_v,profit_id_v,reference_v,coalesce(p_payload->>'notes',''),'POSTED','',now(),p_user_id,now(),p_user_id); final_status:=upper(coalesce(nullif(p_payload->>'status',''),'SOLD_CLOSED')); if final_status not in ('SOLD_CLOSED','COMPLETED') then final_status:='SOLD_CLOSED'; end if; update public.investments set status=final_status,total_invested=cost,principal_returned=principal_total,closure_id=closure_id_v,closed_at=date_v,selling_amount=selling,profit_generated=round(coalesce((select sum(amount) from public.investment_returns where investment_id=inv.investment_id and type='PROFIT' and status='POSTED'),0)+profit_v,2),loss_generated=loss_v,closing_reference=reference_v,close_notes=coalesce(p_payload->>'notes',''),closed_by=p_user_id,updated_at=now(),updated_by=p_user_id where investment_id=inv.investment_id; perform public.nd_create_audit(p_user_id,'CLOSE','INVESTMENT',inv.investment_id,to_jsonb(inv),jsonb_build_object('closureId',closure_id_v,'sellingAmount',selling,'cashReceived',cash,'profit',profit_v,'loss',loss_v,'status',final_status),coalesce(nullif(p_payload->>'reason',''),'Investment sold/closed')); return jsonb_build_object('ok',true,'investmentId',inv.investment_id,'closureId',closure_id_v,'txnId',txn_id_v,'profitId',profit_id_v,'totalCost',cost,'sellingAmount',selling,'cashReceived',cash,'principalReturned',principal_total,'profit',profit_v,'loss',loss_v,'status',final_status);
end $$;

create or replace function public.nd_create_profit_record(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare source public.profit_sources; amount_v numeric; account public.bank_accounts; date_v date; txn_id_v text; profit_id_v text; income_coa public.chart_of_accounts; description_v text;
begin
 select * into source from public.profit_sources where source_id=p_payload->>'sourceId' and status='ACTIVE'; if source.source_id is null then raise exception 'Active profit source required.'; end if; amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Profit amount required.'; end if; perform public.nd_profit_period(p_payload); select * into account from public.bank_accounts where account_id=coalesce(nullif(p_payload->>'accountId',''),'ACC-BANK') and status='ACTIVE'; if account.account_id is null then raise exception 'Payment account not found.'; end if; date_v:=coalesce(nullif(p_payload->>'profitDate','')::date,public.nd_today()); txn_id_v:=public.nd_next_id('TXN','TRX-',8); description_v:=coalesce(nullif(p_payload->>'description',''),'Profit: '||source.source_name);
 insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by) values(txn_id_v,date_v,'','PROFIT_ENTRY','PROFIT',description_v,'CREDIT',amount_v,0,amount_v,0,account.account_id,coalesce(nullif(p_payload->>'paymentMethod',''),account.type),coalesce(p_payload->>'reference',''),'','','POSTED','','',now(),p_user_id,now(),p_user_id); income_coa:=case when coalesce(source.investment_id,'')<>'' then public.nd_coa_by_system('INVESTMENT_INCOME') else public.nd_coa_by_system('OTHER_INCOME') end; perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',account.account_code,'debit',amount_v,'credit',0),jsonb_build_object('accountCode',income_coa.account_code,'debit',0,'credit',amount_v)),'',source.source_id,description_v); profit_id_v:=public.nd_create_profit_record_core(p_user_id,p_payload||jsonb_build_object('sourceId',source.source_id,'investmentId',coalesce(nullif(p_payload->>'investmentId',''),source.investment_id),'category',coalesce(nullif(p_payload->>'category',''),source.category),'profitDate',date_v,'amount',amount_v,'sourceTxnId',txn_id_v)); update public.transactions set related_id=profit_id_v where txn_id=txn_id_v; perform public.nd_create_audit(p_user_id,'CREATE','PROFIT_RECORD',profit_id_v,'{}'::jsonb,(select to_jsonb(p) from public.profit_records p where profit_id=profit_id_v),'Profit posted'); return jsonb_build_object('ok',true,'profitId',profit_id_v,'txnId',txn_id_v);
end $$;

create or replace function public.nd_create_profit_distribution_draft(p_user_id text,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare pr public.profit_records; amount_v numeric; available numeric; basis_type text; dist_date date; dist_id text; ref_v text; total_basis numeric:=0; total_units numeric:=0; member_count_v integer:=0; total_cents bigint; used_cents bigint; left_cents bigint; total_rate_units bigint:=10000; temp_rate_used bigint; r record; item jsonb; manual_sum numeric:=0; source public.profit_sources;
begin
 select * into pr from public.profit_records where profit_id=p_payload->>'profitId' for update; if pr.profit_id is null or pr.status in ('REVERSED','CANCELLED') then raise exception 'Profit record is not distributable.'; end if; amount_v:=round(coalesce((p_payload->>'amount')::numeric,0),2); if amount_v<=0 then raise exception 'Distributable amount required.'; end if; available:=round(greatest(0,pr.amount-public.nd_profit_reserved_amount(pr.profit_id)),2); if amount_v>available+0.009 then raise exception 'Only % remains available for distribution.',available; end if; basis_type:=upper(coalesce(nullif(p_payload->>'basisType',''),'SAVINGS')); if basis_type='UNIT' then basis_type:='UNITS'; end if; if basis_type not in ('MANUAL','SAVINGS','EQUAL','UNITS') then raise exception 'Distribution basis must be MANUAL, SAVINGS, EQUAL or UNITS.'; end if; dist_date:=coalesce(nullif(p_payload->>'distributionDate','')::date,public.nd_today()); dist_id:=public.nd_next_id('PROFIT_DISTRIBUTION_HEADER','PDS-',8); ref_v:=coalesce(nullif(p_payload->>'reference',''),dist_id); select * into source from public.profit_sources where source_id=pr.source_id;
 insert into public.profit_distributions(distribution_id,profit_id,source_id,investment_id,period_type,period_start,period_end,period_label,total_profit,requested_amount,distributed_amount,member_count,basis_type,status,reference,notes,approved_by,approved_at,created_at,created_by,updated_at,updated_by,total_basis,total_units,distribution_date) values(dist_id,pr.profit_id,pr.source_id,coalesce(pr.investment_id,''),pr.period_type,pr.period_start,pr.period_end,pr.period_label,pr.amount,amount_v,0,0,basis_type,'DRAFT',ref_v,coalesce(p_payload->>'notes',''),'',null,now(),p_user_id,now(),p_user_id,0,0,dist_date);
 total_cents:=round(amount_v*100);
 if basis_type='MANUAL' then
   if jsonb_typeof(p_payload->'items')<>'array' or jsonb_array_length(p_payload->'items')=0 then raise exception 'Manual distribution requires member allocations.'; end if;
   create temporary table if not exists nd_dist_tmp(member_id text primary key,name text,basis numeric,amount numeric,rate numeric,units numeric) on commit drop; truncate nd_dist_tmp;
   for item in select * from jsonb_array_elements(p_payload->'items') loop
     if coalesce(item->>'memberId','')='' then raise exception 'Every allocation requires a member.'; end if; if not exists(select 1 from public.members where member_id=item->>'memberId' and status='ACTIVE') then raise exception 'Allocation member is not active: %',item->>'memberId'; end if;
     insert into nd_dist_tmp(member_id,name,basis,amount,rate,units) select m.member_id,coalesce(nullif(m.name_bn,''),m.name_en,m.member_id),0,round((item->>'amount')::numeric,2),0,0 from public.members m where m.member_id=item->>'memberId'; manual_sum:=manual_sum+round((item->>'amount')::numeric,2);
   end loop;
   if abs(round(manual_sum,2)-amount_v)>0.009 then raise exception 'Member allocation total (%) must equal distribution amount (%).',manual_sum,amount_v; end if; total_basis:=0;
   with x as (select member_id,amount, floor(total_rate_units*amount/nullif(manual_sum,0))::bigint base, total_rate_units*amount/nullif(manual_sum,0)-floor(total_rate_units*amount/nullif(manual_sum,0)) rem from nd_dist_tmp), y as (select *,row_number() over(order by rem desc,member_id) rn,sum(base) over() used from x) update nd_dist_tmp t set rate=(y.base+case when y.rn<=total_rate_units-y.used then 1 else 0 end)/100.0 from y where t.member_id=y.member_id;
 else
   create temporary table if not exists nd_dist_tmp(member_id text primary key,name text,basis numeric,amount numeric,rate numeric,units numeric) on commit drop; truncate nd_dist_tmp;
   insert into nd_dist_tmp(member_id,name,basis,amount,rate,units)
   select m.member_id,coalesce(nullif(m.name_bn,''),m.name_en,m.member_id),case when basis_type='EQUAL' then 1 when basis_type='UNITS' then coalesce((select su.units from public.savings_units su where su.member_id=m.member_id and su.status='ACTIVE' and su.effective_from<=dist_date and (su.effective_to is null or su.effective_to>=dist_date) order by su.effective_from desc limit 1),0) else greatest(0,public.nd_member_savings_balance(m.member_id)) end,0,0,case when basis_type='UNITS' then coalesce((select su.units from public.savings_units su where su.member_id=m.member_id and su.status='ACTIVE' and su.effective_from<=dist_date and (su.effective_to is null or su.effective_to>=dist_date) order by su.effective_from desc limit 1),0) else 0 end from public.members m where m.status='ACTIVE';
   if basis_type='SAVINGS' then delete from nd_dist_tmp where basis<=0; end if; select round(coalesce(sum(basis),0),2) into total_basis from nd_dist_tmp; if total_basis<=0 then if basis_type='UNITS' then raise exception 'Total units cannot be zero.'; else raise exception 'No eligible member basis found.'; end if; end if; if basis_type='UNITS' then total_units:=total_basis; end if;
   with x as (select member_id,basis,floor(total_cents*basis/total_basis)::bigint base,total_cents*basis/total_basis-floor(total_cents*basis/total_basis) rem from nd_dist_tmp), y as (select *,row_number() over(order by (basis>0) desc,rem desc,member_id) rn,sum(base) over() used from x) update nd_dist_tmp t set amount=(y.base+case when y.rn<=total_cents-y.used then 1 else 0 end)/100.0 from y where t.member_id=y.member_id;
   with x as (select member_id,basis,floor(total_rate_units*basis/total_basis)::bigint base,total_rate_units*basis/total_basis-floor(total_rate_units*basis/total_basis) rem from nd_dist_tmp), y as (select *,row_number() over(order by (basis>0) desc,rem desc,member_id) rn,sum(base) over() used from x) update nd_dist_tmp t set rate=(y.base+case when y.rn<=total_rate_units-y.used then 1 else 0 end)/100.0 from y where t.member_id=y.member_id;
 end if;
 select count(*) into member_count_v from nd_dist_tmp; if basis_type='MANUAL' then select coalesce(sum(amount),0) into total_basis from nd_dist_tmp; total_basis:=0; end if;
 for r in select * from nd_dist_tmp order by member_id loop insert into public.profit_distribution(dist_id,financial_year,member_id,basis_amount,rate,amount,status,txn_id,approved_by,approved_at,created_at,created_by,distribution_id,profit_id,source_id,investment_id,period_type,period_start,period_end,period_label,reference,updated_at,updated_by,basis_type,unit_quantity,total_units,unit_percentage,member_name) values(public.nd_next_id('DIST','DST-',8),to_char(pr.period_start,'YYYY'),r.member_id,r.basis,r.rate,r.amount,'DRAFT','', '',null,now(),p_user_id,dist_id,pr.profit_id,pr.source_id,coalesce(pr.investment_id,''),pr.period_type,pr.period_start,pr.period_end,pr.period_label,ref_v,now(),p_user_id,basis_type,case when basis_type='UNITS' then r.units else 0 end,case when basis_type='UNITS' then total_units else 0 end,case when basis_type='UNITS' then r.rate else 0 end,r.name); end loop;
 update public.profit_distributions set member_count=member_count_v,total_basis=case when basis_type='MANUAL' then 0 else total_basis end,total_units=total_units where distribution_id=dist_id; perform public.nd_create_audit(p_user_id,'CREATE','PROFIT_DISTRIBUTION',dist_id,'{}'::jsonb,jsonb_build_object('profitId',pr.profit_id,'source',source.source_name,'method',basis_type,'totalUnits',total_units),'Profit distribution draft'); return jsonb_build_object('ok',true,'distributionId',dist_id,'count',member_count_v,'total',amount_v,'remaining',round(available-amount_v,2),'totalUnits',total_units,'basisType',basis_type);
end $$;

create or replace function public.nd_approve_profit_distribution(p_user_id text,p_distribution_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare h public.profit_distributions; pr public.profit_records; capacity numeric; a public.profit_distribution; txn_id_v text; description_v text; retained public.chart_of_accounts; saving public.chart_of_accounts; date_v date; distributed numeric; count_v integer:=0; final_status text;
begin
 select * into h from public.profit_distributions where distribution_id=p_distribution_id for update; if h.distribution_id is null or h.status not in ('DRAFT','PROCESSING') then raise exception 'Draft distribution not found or already processed.'; end if; select * into pr from public.profit_records where profit_id=h.profit_id for update; if pr.profit_id is null or pr.status in ('REVERSED','CANCELLED') then raise exception 'Profit record is not distributable.'; end if; capacity:=round(pr.amount-greatest(0,public.nd_profit_reserved_amount(pr.profit_id)-h.requested_amount),2); if h.requested_amount>capacity+0.009 then raise exception 'Profit remaining is insufficient.'; end if; date_v:=coalesce(h.distribution_date,public.nd_today()); update public.profit_distributions set status='PROCESSING',distribution_date=date_v,updated_at=now(),updated_by=p_user_id where distribution_id=p_distribution_id; retained:=public.nd_coa_by_system('RETAINED_SURPLUS'); saving:=public.nd_coa_by_system('MEMBER_SAVINGS');
 for a in select * from public.profit_distribution where distribution_id=p_distribution_id order by member_id for update loop
   if a.status in ('APPROVED','ZERO_ALLOCATION') then continue; end if; if a.status<>'DRAFT' then raise exception 'Allocation % is not processable.',a.dist_id; end if; if a.amount<=0 then update public.profit_distribution set status='ZERO_ALLOCATION',updated_at=now(),updated_by=p_user_id where dist_id=a.dist_id; continue; end if; txn_id_v:=public.nd_next_id('TXN','TRX-',8); description_v:='Profit distribution '||h.period_label||' · '||h.distribution_id;
   insert into public.transactions(txn_id,txn_date,member_id,type,category,description,direction,amount,principal_amount,profit_amount,penalty_amount,payment_account_id,payment_method,reference,related_id,receipt_id,status,parent_txn_id,correction_reason,created_at,created_by,updated_at,updated_by) values(txn_id_v,date_v,a.member_id,'PROFIT_DISTRIBUTION','SAVINGS',description_v,'CREDIT',a.amount,0,a.amount,0,'','INTERNAL',coalesce(h.reference,h.distribution_id),h.distribution_id,'','POSTED','','',now(),p_user_id,now(),p_user_id);
   perform public.nd_post_journal(p_user_id,txn_id_v,date_v,jsonb_build_array(jsonb_build_object('accountCode',retained.account_code,'debit',a.amount,'credit',0),jsonb_build_object('accountCode',saving.account_code,'debit',0,'credit',a.amount)),a.member_id,h.distribution_id,description_v); update public.profit_distribution set status='APPROVED',txn_id=txn_id_v,approved_by=p_user_id,approved_at=now(),updated_at=now(),updated_by=p_user_id where dist_id=a.dist_id; perform public.nd_create_notification(a.member_id,'PROFIT','মুনাফা বণ্টন','আপনার হিসাবে '||a.amount||' টাকা মুনাফা যোগ হয়েছে। Ref: '||h.distribution_id); count_v:=count_v+1;
 end loop;
 distributed:=public.nd_distribution_approved_amount(p_distribution_id); final_status:=case when distributed+0.009>=h.requested_amount then 'APPROVED' else 'PROCESSING' end; update public.profit_distributions set distributed_amount=distributed,status=final_status,approved_by=case when final_status='APPROVED' then p_user_id else '' end,approved_at=case when final_status='APPROVED' then now() else null end,updated_at=now(),updated_by=p_user_id where distribution_id=p_distribution_id; perform public.nd_refresh_profit_record(h.profit_id,p_user_id); perform public.nd_create_audit(p_user_id,'APPROVE','PROFIT_DISTRIBUTION',p_distribution_id,to_jsonb(h),jsonb_build_object('distributedAmount',distributed,'status',final_status,'creditedMembers',count_v),'Profit distribution approved and member accounts credited'); return jsonb_build_object('ok',true,'distributionId',p_distribution_id,'count',count_v,'memberCount',h.member_count,'distributedAmount',distributed,'status',final_status);
end $$;
